packages:
- apps/*
- packages/*
- tooling/*
catalog:
  '@auth/core': 0.37.2
  eslint: ^9.25.1
  prettier: ^3.5.3
  tailwindcss: ^4.1.8
  typescript: ^5.8.3
  zod: ^3.24.3
  '@tanstack/react-query': ^5.69.0
  '@trpc/react-query': ^11.1.0
  '@trpc/client': ^11.1.0
  '@trpc/tanstack-react-query': ^11.1.0
  '@trpc/server': ^11.1.0
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.0.12
    '@types/react-dom': ^19.0.4
