name: 'Deploy to Cloud Run'
description: 'Deploy MCP Proxy to Google Cloud Run'

inputs:
  environment:
    description: 'Deployment environment (staging|production)'
    required: true
  gcp_credentials:
    description: 'GCP service account credentials JSON'
    required: true
  gcp_project_id:
    description: 'GCP project ID'
    required: true
  region:
    description: 'Cloud Run region'
    default: 'asia-northeast1'
    required: false
  min_instances:
    description: 'Minimum number of instances'
    default: '0'
    required: false
  max_instances:
    description: 'Maximum number of instances'
    default: '3'
    required: false

outputs:
  service_url:
    description: 'Cloud Run service URL'
    value: ${{ steps.deploy.outputs.service_url }}
  health_url:
    description: 'Health check URL'
    value: ${{ steps.deploy.outputs.health_url }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      shell: bash
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build Docker image
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      run: |
        echo "🚀 Starting Cloud Run deployment"
        echo "Environment: $ENVIRONMENT"

        # Get short SHA
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "Commit SHA: $SHORT_SHA"

        # Build Docker image
        echo "🔨 Building Docker image..."
        docker build \
          -t asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki/mcp-proxy:$ENVIRONMENT-$SHORT_SHA \
          -t asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki/mcp-proxy:$ENVIRONMENT-latest \
          -f apps/mcp-proxy/Dockerfile \
          .

        echo "✅ Docker image built successfully"

    - name: Push Docker image
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)

        # Push images to Artifact Registry
        echo "📦 Pushing Docker images to Artifact Registry..."
        docker push asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki/mcp-proxy:$ENVIRONMENT-$SHORT_SHA
        docker push asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki/mcp-proxy:$ENVIRONMENT-latest

        echo "✅ Docker images pushed successfully"

    - name: Deploy to Cloud Run
      id: deploy
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
        REGION: ${{ inputs.region }}
        MIN_INSTANCES: ${{ inputs.min_instances }}
        MAX_INSTANCES: ${{ inputs.max_instances }}
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        SERVICE_NAME="tumiki-mcp-proxy-$ENVIRONMENT"

        echo "🚀 Deploying to Cloud Run..."
        echo "Region: $REGION"
        echo "Scaling: Min $MIN_INSTANCES / Max $MAX_INSTANCES"

        # Deploy to Cloud Run
        gcloud run deploy "$SERVICE_NAME" \
          --image=asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki/mcp-proxy:$ENVIRONMENT-$SHORT_SHA \
          --region="$REGION" \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=512Mi \
          --cpu=1 \
          --timeout=60s \
          --concurrency=80 \
          --min-instances="$MIN_INSTANCES" \
          --max-instances="$MAX_INSTANCES" \
          --set-env-vars=NODE_ENV=production,PORT=8080,LOG_LEVEL=info \
          --set-secrets=DATABASE_URL=tumiki-database-url-$ENVIRONMENT:latest,UPSTASH_REDIS_REST_URL=tumiki-redis-url:latest,UPSTASH_REDIS_REST_TOKEN=tumiki-redis-token:latest,CACHE_ENCRYPTION_KEY=tumiki-cache-encryption-key-$ENVIRONMENT:latest \
          --service-account=tumiki-mcp-proxy@$GCP_PROJECT_ID.iam.gserviceaccount.com \
          --vpc-connector=tumiki-vpc-connector \
          --vpc-egress=private-ranges-only

        # Get service URL
        SERVICE_URL=$(gcloud run services describe "$SERVICE_NAME" \
          --region="$REGION" \
          --project="$GCP_PROJECT_ID" \
          --format='value(status.url)')

        echo "✅ Deployment completed"
        echo "Service URL: $SERVICE_URL"

        # Output for GitHub Actions
        echo "service_url=$SERVICE_URL" >> $GITHUB_OUTPUT
        echo "health_url=$SERVICE_URL/health" >> $GITHUB_OUTPUT

    - name: Verify deployment
      shell: bash
      env:
        SERVICE_URL: ${{ steps.deploy.outputs.service_url }}
      run: |
        echo "🔍 Verifying deployment..."

        # Wait for service to be ready
        sleep 10

        # Health check with retries
        for i in {1..5}; do
          if curl -f -s "$SERVICE_URL/health" > /dev/null; then
            echo "✅ Health check passed"
            exit 0
          fi
          echo "⏳ Waiting for service to be ready (attempt $i/5)..."
          sleep 5
        done

        echo "❌ Health check failed"
        exit 1

    - name: Display deployment info
      shell: bash
      env:
        SERVICE_URL: ${{ steps.deploy.outputs.service_url }}
        HEALTH_URL: ${{ steps.deploy.outputs.health_url }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        echo "========================================="
        echo "🎉 Cloud Run Deployment Successful"
        echo "========================================="
        echo "Environment: $ENVIRONMENT"
        echo "Service URL: $SERVICE_URL"
        echo "Health Check: $HEALTH_URL"
        echo "========================================="
