name: 'Deploy to Cloud Run'
description: 'Deploy MCP Proxy to Google Cloud Run'

inputs:
  environment:
    description: 'Deployment environment (preview|staging|production)'
    required: true
  pr_number:
    description: 'PR number for preview deployments (optional, used to create unique service names)'
    required: false
    default: ''
  gcp_credentials:
    description: 'GCP service account credentials JSON'
    required: true
  gcp_project_id:
    description: 'GCP project ID'
    required: true
  region:
    description: 'Cloud Run region'
    default: 'asia-northeast1'
    required: false
  min_instances:
    description: 'Minimum number of instances'
    default: '0'
    required: false
  max_instances:
    description: 'Maximum number of instances'
    default: '3'
    required: false

outputs:
  service_url:
    description: 'Cloud Run service URL'
    value: ${{ steps.deploy.outputs.service_url }}
  health_url:
    description: 'Health check URL'
    value: ${{ steps.deploy.outputs.health_url }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      shell: bash
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build Docker image
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      run: |
        echo "🚀 Starting Cloud Run deployment"
        echo "Environment: $ENVIRONMENT"

        # Get short SHA
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "Commit SHA: $SHORT_SHA"

        # Build Docker image
        echo "🔨 Building Docker image..."
        docker build \
          -t asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki-mcp/mcp-proxy:$ENVIRONMENT-$SHORT_SHA \
          -t asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki-mcp/mcp-proxy:$ENVIRONMENT-latest \
          -f apps/mcp-proxy/Dockerfile \
          .

        echo "✅ Docker image built successfully"

    - name: Push Docker image
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)

        # Push images to Artifact Registry
        echo "📦 Pushing Docker images to Artifact Registry..."
        docker push asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki-mcp/mcp-proxy:$ENVIRONMENT-$SHORT_SHA
        docker push asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki-mcp/mcp-proxy:$ENVIRONMENT-latest

        echo "✅ Docker images pushed successfully"

    - name: Deploy to Cloud Run
      id: deploy
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
        REGION: ${{ inputs.region }}
        MIN_INSTANCES: ${{ inputs.min_instances }}
        MAX_INSTANCES: ${{ inputs.max_instances }}
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)

        # Determine service name and secret environment based on environment
        if [ "$ENVIRONMENT" = "preview" ] && [ -n "$PR_NUMBER" ]; then
          SERVICE_NAME="tumiki-mcp-proxy-pr-$PR_NUMBER"
          SECRET_ENV="staging"  # Preview環境ではstagingのシークレットを使用
          echo "🔵 Preview deployment for PR #$PR_NUMBER (using staging secrets)"
        else
          SERVICE_NAME="tumiki-mcp-proxy-$ENVIRONMENT"
          SECRET_ENV="$ENVIRONMENT"
        fi

        echo "🚀 Deploying to Cloud Run..."
        echo "Service: $SERVICE_NAME"
        echo "Region: $REGION"
        echo "Scaling: Min $MIN_INSTANCES / Max $MAX_INSTANCES"

        # VPCコネクターの設定（preview環境では使用しない）
        VPC_ARGS=""
        if [ "$ENVIRONMENT" != "preview" ]; then
          VPC_ARGS="--vpc-connector=tumiki-vpc-connector --vpc-egress=private-ranges-only"
          echo "VPC: tumiki-vpc-connector (private-ranges-only)"
        else
          VPC_ARGS="--clear-vpc-connector"
          echo "VPC: Clearing VPC connector for preview environment"
        fi

        # Deploy to Cloud Run
        gcloud run deploy "$SERVICE_NAME" \
          --image=asia-northeast1-docker.pkg.dev/$GCP_PROJECT_ID/tumiki-mcp/mcp-proxy:$ENVIRONMENT-$SHORT_SHA \
          --region="$REGION" \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=512Mi \
          --cpu=1 \
          --timeout=60s \
          --concurrency=80 \
          --min-instances="$MIN_INSTANCES" \
          --max-instances="$MAX_INSTANCES" \
          --set-env-vars=NODE_ENV=production,LOG_LEVEL=info,LOG_DESTINATION=stdout \
          --set-secrets=DATABASE_URL=tumiki-database-url-$SECRET_ENV:latest,UPSTASH_REDIS_REST_URL=tumiki-redis-url:latest,UPSTASH_REDIS_REST_TOKEN=tumiki-redis-token:latest,CACHE_ENCRYPTION_KEY=tumiki-cache-encryption-key-$SECRET_ENV:latest \
          --service-account=tumiki-mcp-proxy@$GCP_PROJECT_ID.iam.gserviceaccount.com \
          --no-cpu-throttling \
          $VPC_ARGS

        # Get service URL
        SERVICE_URL=$(gcloud run services describe "$SERVICE_NAME" \
          --region="$REGION" \
          --project="$GCP_PROJECT_ID" \
          --format='value(status.url)')

        echo "✅ Deployment completed"
        echo "Service URL: $SERVICE_URL"

        # Output for GitHub Actions
        echo "service_url=$SERVICE_URL" >> $GITHUB_OUTPUT
        echo "health_url=$SERVICE_URL/health" >> $GITHUB_OUTPUT

    - name: Verify deployment
      shell: bash
      env:
        SERVICE_URL: ${{ steps.deploy.outputs.service_url }}
      run: |
        echo "🔍 Verifying deployment..."

        # Wait for service to be ready
        sleep 10

        # Health check with retries
        for i in {1..5}; do
          if curl -f -s "$SERVICE_URL/health" > /dev/null; then
            echo "✅ Health check passed"
            exit 0
          fi
          echo "⏳ Waiting for service to be ready (attempt $i/5)..."
          sleep 5
        done

        echo "❌ Health check failed"
        exit 1

    - name: Setup custom domain
      if: inputs.environment == 'staging' || inputs.environment == 'production'
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
        REGION: ${{ inputs.region }}
      run: |
        # Define custom domain for staging/production only
        if [ "$ENVIRONMENT" = "production" ]; then
          CUSTOM_DOMAIN="server.tumiki.cloud"
        else
          CUSTOM_DOMAIN="stg-server.tumiki.cloud"
        fi

        SERVICE_NAME="tumiki-mcp-proxy-$ENVIRONMENT"

        echo "🌐 Setting up custom domain: $CUSTOM_DOMAIN"

        # Check if domain mapping already exists
        if gcloud run domain-mappings describe "$CUSTOM_DOMAIN" \
            --region="$REGION" \
            --project="$GCP_PROJECT_ID" >/dev/null 2>&1; then
          echo "✅ Custom domain already configured"

          # Check certificate status
          CERT_STATUS=$(gcloud run domain-mappings describe "$CUSTOM_DOMAIN" \
            --region="$REGION" \
            --project="$GCP_PROJECT_ID" \
            --format='value(status.conditions[0].status)' 2>/dev/null || echo "Unknown")

          if [ "$CERT_STATUS" = "True" ]; then
            echo "✅ SSL certificate is ready"
          else
            echo "⏳ SSL certificate is provisioning (this may take several minutes)"
            echo "   Current status: $CERT_STATUS"
          fi
        else
          echo "⚠️  Custom domain not configured yet"
          echo "📝 Creating domain mapping..."

          # Create domain mapping
          if gcloud run domain-mappings create \
              --service="$SERVICE_NAME" \
              --domain="$CUSTOM_DOMAIN" \
              --region="$REGION" \
              --project="$GCP_PROJECT_ID"; then
            echo "✅ Domain mapping created"
            echo ""
            echo "⚠️  DNS CONFIGURATION REQUIRED"
            echo "================================================"
            echo "Please add the following DNS record:"
            echo ""
            echo "  Type:  CNAME"
            echo "  Name:  ${CUSTOM_DOMAIN%%.*}"
            echo "  Value: ghs.googlehosted.com"
            echo "  TTL:   3600"
            echo ""
            echo "SSL certificate will be automatically provisioned"
            echo "after DNS propagation (may take up to 48 hours)."
            echo "================================================"
          else
            echo "❌ Failed to create domain mapping"
            echo "   This is not critical - deployment will continue"
            echo "   You can set up custom domain manually later"
            echo "   See: docs/cloudrun-custom-domain.md"
          fi
        fi

    - name: Display deployment info
      shell: bash
      env:
        SERVICE_URL: ${{ steps.deploy.outputs.service_url }}
        HEALTH_URL: ${{ steps.deploy.outputs.health_url }}
        ENVIRONMENT: ${{ inputs.environment }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        echo "========================================="
        echo "🎉 Cloud Run Deployment Successful"
        echo "========================================="
        echo "Environment: $ENVIRONMENT"

        if [ "$ENVIRONMENT" = "preview" ] && [ -n "$PR_NUMBER" ]; then
          echo "PR: #$PR_NUMBER"
          echo "Service: tumiki-mcp-proxy-pr-$PR_NUMBER"
        fi

        echo "Service URL: $SERVICE_URL"

        # Display custom domain for staging/production
        if [ "$ENVIRONMENT" = "production" ]; then
          echo "Custom Domain: https://server.tumiki.cloud"
        elif [ "$ENVIRONMENT" = "staging" ]; then
          echo "Custom Domain: https://stg-server.tumiki.cloud"
        fi

        echo "Health Check: $HEALTH_URL"
        echo "========================================="
