import type { Prisma } from "@prisma/client";

/**
 * db に登録する MCP サーバー一覧
 */
export const MCP_SERVERS = [
  {
    name: "Notion MCP",
    iconPath: "/logos/notion.svg",
    command: "node",
    args: ["node_modules/@suekou/mcp-notion-server/build/index.js"],
    envVars: ["NOTION_API_TOKEN"],
    isPublic: true,
  },
  {
    name: "GitHub MCP",
    iconPath: "/logos/github.svg",
    command: "node",
    args: ["node_modules/@modelcontextprotocol/server-github/dist/index.js"],
    envVars: ["GITHUB_PERSONAL_ACCESS_TOKEN"],
    isPublic: true,
  },
  {
    name: "Context7",
    iconPath: "/logos/context7.svg",
    command: "node",
    args: ["node_modules/@upstash/context7-mcp/dist/index.js"],
    isPublic: true,
  },
  {
    name: "Playwright MCP",
    iconPath: "/logos/playwright.svg",
    command: "node",
    args: ["node_modules/@playwright/mcp/cli.js"],
    isPublic: true,
  },
  // {
  //   // ローカルでないと意味ない
  //   name: "Task Master AI",
  //   iconPath: "/logos/task-master.svg",
  //   command: "node",
  //   args: ["node_modules/task-master-ai/mcp-server/server.js"],
  //   envVars: [
  //     "ANTHROPIC_API_KEY",
  //     "PERPLEXITY_API_KEY",
  //     "OPENAI_API_KEY",
  //     "GOOGLE_API_KEY",
  //     "MISTRAL_API_KEY",
  //     "OPENROUTER_API_KEY",
  //     "XAI_API_KEY",
  //     "AZURE_OPENAI_API_KEY",
  //     "OLLAMA_API_KEY",
  //   ],
  //   isPublic: false,
  // },
  {
    name: "Figma",
    iconPath: "/logos/figma.svg",
    command: "node",
    args: [
      "node_modules/figma-developer-mcp/dist/index.js",
      "--figma-api-key=FIGMA_API_KEY",
      "--figma-oauth-token=FIGMA_OAUTH_TOKEN",
      "--stdio",
    ],
    envVars: ["FIGMA_API_KEY", "FIGMA_OAUTH_TOKEN"],
    isPublic: true,
  },
  // {
  //   name: "Puppeteer MCP",
  //   iconPath: "/logos/puppeteer.png",
  //   command: "node",
  //   args: [
  //     "node_modules/puppeteer-mcp-server/dist/index.js",
  //     "--headless=true",
  //     "--no-sandbox",
  //     "--disable-setuid-sandbox",
  //     "--disable-dev-shm-usage",
  //     "--disable-gpu",
  //   ],
  //   envVars: [],
  //   isPublic: true,
  // },
  // {
  //   name: "Gemini Google Search",
  //   iconPath: "/logos/gemini-search.png",
  //   command: "node",
  //   args: ["node_modules/mcp-gemini-google-search/dist/index.js"],
  //   envVars: ["GEMINI_API_KEY", "GEMINI_MODEL"],
  //   isPublic: true,
  // },
  {
    name: "Slack MCP",
    iconPath: "/logos/slack.svg",
    command: "node",
    args: ["node_modules/slack-mcp-server/bin/index.js"],
    envVars: ["SLACK_MCP_XOXP_TOKEN"],
    isPublic: true,
  },
  {
    name: "Discord MCP",
    iconPath: "/logos/discord.svg",
    command: "node",
    args: ["node_modules/discord-mcp-server/build/index.js"],
    envVars: ["DISCORD_TOKEN"],
    isPublic: true,
  },
  {
    name: "LINE Bot MCP",
    iconPath: "/logos/line.svg",
    command: "node",
    args: ["node_modules/@line/line-bot-mcp-server/dist/index.js"],
    envVars: ["CHANNEL_ACCESS_TOKEN", "DESTINATION_USER_ID"],
    isPublic: true,
  },
  {
    name: "DeepL MCP",
    iconPath: "/logos/deepl.svg",
    command: "node",
    args: ["node_modules/deepl-mcp-server/src/index.mjs"],
    envVars: ["DEEPL_API_KEY"],
    isPublic: true,
  },
  {
    name: "microCMS MCP",
    iconPath: "/logos/microcms.svg",
    command: "node",
    args: ["node_modules/microcms-mcp-server/dist/index.js"],
    envVars: ["MICROCMS_SERVICE_ID", "MICROCMS_API_KEY"],
    isPublic: true,
  },
  {
    name: "Google Search Console",
    iconPath: "/logos/google-search-console.svg",
    command: "node",
    args: ["node_modules/mcp-server-gsc/dist/index.js"],
    envVars: ["GOOGLE_APPLICATION_CREDENTIALS"],
    isPublic: true,
  },
  {
    name: "n8n MCP",
    iconPath: "/logos/n8n.png",
    command: "node",
    args: ["node_modules/n8n-mcp/dist/mcp/index.js"],
    envVars: [
      "MCP_MODE",
      "LOG_LEVEL",
      "DISABLE_CONSOLE_OUTPUT",
      "N8N_API_URL",
      "N8N_API_KEY"
    ],
  },
  {
    name: "Microsoft Clarity",
    iconPath: "/logos/microsoft-clarity.png",
    command: "node",
    args: ["node_modules/@microsoft/clarity-mcp-server/dist/cli.js"],
    envVars: ["CLARITY_API_TOKEN"],
    isPublic: true,
  },
] as const satisfies Prisma.McpServerCreateWithoutToolsInput[];
