apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "internal-manager.namespace" . }}
  labels:
    {{- include "internal-manager.labels" . | nindent 4 }}
    tumiki/tenant: {{ .Values.tenant.slug | quote }}
