apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ include "internal-manager.namespace" . }}
  labels:
    {{- include "internal-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: internal-manager
    app.kubernetes.io/instance: {{ .Values.tenant.slug }}
    app.kubernetes.io/component: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
