apiVersion: v1
kind: Service
metadata:
  name: internal-manager
  namespace: {{ include "internal-manager.namespace" . }}
  labels:
    {{- include "internal-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: internal-manager
    app.kubernetes.io/instance: {{ .Values.tenant.slug }}
    app.kubernetes.io/component: app
  ports:
    - port: 3100
      targetPort: 3100
      name: http
