import type { JSX } from "react";
import { useState, useMemo, useEffect, useCallback } from "react";
import { X, Info, ChevronDown } from "lucide-react";
import type { CatalogItem } from "../../types/catalog";
import {
  FILESYSTEM_STDIO_NAME,
  OUTLINE_MCP_NAME,
} from "../../shared/catalog.constants";
import { formatCatalogDisplayName } from "../../shared/catalog.helpers";
import { toSlug } from "../../shared/mcp.slug";
import {
  FALLBACK_SLUG_PLACEHOLDER,
  SLUG_FALLBACK_PREFIX,
} from "../../shared/mcp.constants";
import {
  DISCOVERY_ERROR_CODE,
  extractOAuthErrorCode,
} from "../../shared/oauth/discovery-error-codes";
import { OAuthCallbackUrlField } from "./OAuthCallbackUrlField";

type AddMcpModalProps = {
  catalog: CatalogItem;
  onClose: () => void;
  onSuccess: (serverName: string) => void;
  /** DCR 非対応が事前検出済みの場合、OAuth クライアント設定を初期表示で開く */
  initialNeedsManualOAuthClient?: boolean;
  /** キャッシュ済み手動入力クライアントIDのプリフィル値 */
  initialOAuthClientId?: string;
  /** キャッシュ済み手動入力クライアントシークレットのプリフィル値 */
  initialOAuthClientSecret?: string;
};

/** 認証タイプの表示ラベル（カタログ指定をそのまま見せる） */
const AUTH_TYPE_LABEL: Record<CatalogItem["authType"], string> = {
  OAUTH: "OAuth認証",
  API_KEY: "API Key",
  BEARER: "Bearer",
  NONE: "認証なし",
};

/** 通信方式の表示ラベル（カタログ指定をそのまま見せる） */
const TRANSPORT_LABEL: Record<CatalogItem["transportType"], string> = {
  STREAMABLE_HTTP: "Streamable HTTP",
  SSE: "SSE",
  STDIO: "stdio",
};

export const AddMcpModal = ({
  catalog,
  onClose,
  onSuccess,
  initialNeedsManualOAuthClient = false,
  initialOAuthClientId,
  initialOAuthClientSecret,
}: AddMcpModalProps): JSX.Element => {
  const template = catalog.connectionTemplate;
  const credentialKeys: string[] = template.credentialKeys;

  const [serverName, setServerName] = useState(
    formatCatalogDisplayName(catalog.name),
  );
  const [credentials, setCredentials] = useState<Record<string, string>>(
    Object.fromEntries(credentialKeys.map((key) => [key, ""])),
  );
  const [showSlugInfo, setShowSlugInfo] = useState(false);
  const [showOAuthSettings, setShowOAuthSettings] = useState(
    initialNeedsManualOAuthClient,
  );
  const [oauthClientId, setOauthClientId] = useState(
    initialOAuthClientId ?? "",
  );
  const [oauthClientSecret, setOauthClientSecret] = useState(
    initialOAuthClientSecret ?? "",
  );
  /** DCR非対応サーバー用: client_id/secret 手動入力が必要なフラグ */
  const [needsManualOAuthClient, setNeedsManualOAuthClient] = useState(
    initialNeedsManualOAuthClient,
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isFilesystemStdio = catalog.name === FILESYSTEM_STDIO_NAME;
  const isOutline = catalog.name === OUTLINE_MCP_NAME;
  const [directoryPath, setDirectoryPath] = useState("");
  const [customUrl, setCustomUrl] = useState(template.url ?? "");

  const slug = useMemo(() => toSlug(serverName), [serverName]);
  const isAutoGeneratedSlug = slug === "";
  const isOAuth = template.authType === "OAUTH";

  const needsApiKey =
    (template.authType === "API_KEY" || template.authType === "BEARER") &&
    credentialKeys.length > 0;
  const hasRequiredCredentials =
    !needsApiKey ||
    credentialKeys.every((key) => (credentials[key] ?? "").trim() !== "");

  // OAuth成功/エラーイベントのリスナー
  const handleOAuthSuccess = useCallback(
    (result: { serverId: number; serverName: string }) => {
      setLoading(false);
      onSuccess(result.serverName);
    },
    [onSuccess],
  );

  const handleOAuthError = useCallback((errorMsg: string) => {
    setLoading(false);
    setError(errorMsg);
    setNeedsManualOAuthClient(false);
  }, []);

  useEffect(() => {
    if (!isOAuth) return;
    const unsubSuccess =
      window.electronAPI.oauth.onOAuthSuccess(handleOAuthSuccess);
    const unsubError = window.electronAPI.oauth.onOAuthError(handleOAuthError);
    return () => {
      unsubSuccess();
      unsubError();
    };
  }, [isOAuth, handleOAuthSuccess, handleOAuthError]);

  // DCR非対応検知時はアコーディオンを自動展開
  useEffect(() => {
    if (needsManualOAuthClient) setShowOAuthSettings(true);
  }, [needsManualOAuthClient]);

  // Escape キーでモーダルを閉じる（OAuth 認証中はキャンセル扱い）
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent): void => {
      if (e.key !== "Escape") return;
      if (isOAuth && loading) {
        window.electronAPI.oauth.cancelAuth();
      }
      onClose();
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [onClose, isOAuth, loading]);

  const handleSubmit = async (): Promise<void> => {
    if (!serverName.trim()) {
      setError("サーバー名を入力してください");
      return;
    }
    if (!hasRequiredCredentials) {
      setError("すべてのAPIキーを入力してください");
      return;
    }

    if (isFilesystemStdio && !directoryPath.trim()) {
      setError("アクセスディレクトリを入力してください");
      return;
    }

    if (isOutline && !customUrl.trim()) {
      setError("サーバーURLを入力してください");
      return;
    }

    setLoading(true);
    setError(null);

    let resolvedArgs = template.args;
    if (isFilesystemStdio) {
      resolvedArgs = [...template.args, directoryPath.trim()];
    }

    // OAuth認証フロー
    if (isOAuth) {
      if (needsManualOAuthClient && !oauthClientId.trim()) {
        setError("Client IDを入力してください");
        setLoading(false);
        return;
      }
      if (!template.url) {
        setError("カタログにサーバーURLが設定されていません");
        setLoading(false);
        return;
      }
      try {
        await window.electronAPI.oauth.startAuth({
          catalogName: serverName,
          description: catalog.description,
          transportType: template.transportType,
          command: template.command,
          args: JSON.stringify(resolvedArgs),
          url: template.url,
          managerCatalog: {
            catalogId: catalog.id,
            status: catalog.status,
            permissions: catalog.permissions,
            connectionTemplate: {
              ...template,
              args: resolvedArgs,
              url: isOutline ? customUrl : template.url,
            },
            tools: catalog.tools.map((tool) => ({
              name: tool.name,
              allowed: tool.allowed,
            })),
          },
          ...(needsManualOAuthClient && {
            oauthClientId: oauthClientId.trim(),
            oauthClientSecret: oauthClientSecret.trim() || undefined,
          }),
        });
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "OAuth認証の開始に失敗しました";
        const { code, displayMessage } = extractOAuthErrorCode(message);
        if (code === DISCOVERY_ERROR_CODE.DCR_NOT_SUPPORTED) {
          setNeedsManualOAuthClient(true);
          setError(null);
        } else {
          setNeedsManualOAuthClient(false);
          setError(displayMessage);
        }
        setLoading(false);
      }
      return;
    }

    try {
      const result = await window.electronAPI.catalog.add({
        catalogId: catalog.id,
        serverName,
        description: catalog.description,
        status: catalog.status,
        permissions: catalog.permissions,
        connectionTemplate: {
          ...template,
          args: resolvedArgs,
          url: isOutline ? customUrl : template.url,
        },
        tools: catalog.tools.map((tool) => ({
          name: tool.name,
          allowed: tool.allowed,
        })),
        credentials,
      });
      onSuccess(result.serverName);
    } catch (err) {
      // メイン側でtools取得失敗時に整形した日本語メッセージを返すため、Errorのmessageを優先表示する
      const message = err instanceof Error ? err.message : "";
      setError(message || "MCPサーバーの登録に失敗しました");
    } finally {
      setLoading(false);
    }
  };

  const submitLabel = loading
    ? isOAuth
      ? "ブラウザで認証中..."
      : "作成中..."
    : isOAuth
      ? "認証してサーバーを追加"
      : "作成";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-gray-200 bg-white p-8 dark:border-white/[.08] dark:bg-zinc-900">
        {/* タイトル + 閉じるボタン */}
        <div className="mb-1 flex items-start justify-between">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">
            MCPサーバー追加
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-md p-1 text-gray-500 transition hover:opacity-70 dark:text-zinc-500"
          >
            <X size={20} />
          </button>
        </div>

        {/* 説明文 */}
        <p className="mb-6 text-sm text-gray-500 dark:text-zinc-500">
          URLからMCPサーバーを追加します。サーバー情報を入力してください。
        </p>

        {/* サーバー名 */}
        <div className="mb-2">
          <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
            サーバー名<span className="text-red-600 dark:text-red-400">*</span>
          </label>
          <input
            type="text"
            value={serverName}
            onChange={(e) => setServerName(e.target.value)}
            placeholder="例: My Custom MCP Server"
            className="w-full rounded-lg border border-gray-200 bg-black/[.02] px-4 py-3 text-sm text-gray-900 outline-none placeholder:text-gray-400 dark:border-white/[.08] dark:bg-white/[.03] dark:text-white"
          />
          <p className="mt-1.5 text-xs text-gray-500 dark:text-zinc-500">
            表示されるサーバー名を設定できます（空白や大文字を含むことができます）
          </p>
        </div>

        {/* MCP識別子（readonly） */}
        <div
          className="relative mb-6"
          onMouseEnter={() => setShowSlugInfo(true)}
          onMouseLeave={() => setShowSlugInfo(false)}
        >
          <div
            className={`flex w-full items-center gap-1.5 rounded-lg border border-gray-100 px-4 py-3 dark:border-white/[.03] ${
              showSlugInfo
                ? "bg-black/[.06] dark:bg-white/[.08]"
                : "bg-[#e8eaed] dark:bg-[#0a0a0a]"
            }`}
          >
            <span className="text-xs font-medium text-gray-500 dark:text-zinc-500">
              MCPサーバー識別子:
            </span>
            <span className="font-mono text-xs text-gray-600 dark:text-zinc-400">
              {isAutoGeneratedSlug
                ? `${FALLBACK_SLUG_PLACEHOLDER}（自動生成）`
                : slug}
            </span>
            <Info
              size={14}
              className="ml-auto text-gray-400 dark:text-zinc-600"
            />
          </div>
          <div
            className={`pointer-events-none absolute bottom-full left-0 z-10 mb-2 w-80 rounded-lg border border-gray-200 bg-white px-4 py-3 text-xs shadow-lg transition-all duration-150 dark:border-white/[.08] dark:bg-zinc-900 ${
              showSlugInfo
                ? "translate-y-0 opacity-100"
                : "translate-y-1 opacity-0"
            }`}
          >
            <div className="mb-1.5 font-semibold text-gray-900 dark:text-white">
              MCPサーバー識別子の用途
            </div>
            <ul className="list-inside list-disc space-y-1 text-gray-600 dark:text-zinc-400">
              <li>
                ツール名の接頭辞として使用（例:
                {isAutoGeneratedSlug ? FALLBACK_SLUG_PLACEHOLDER : slug}
                __tool_name）
              </li>
              <li>設定ファイルのキーとして使用（Claude Desktop、Cursor等）</li>
              {isAutoGeneratedSlug && (
                <li>
                  サーバー名に英数字が含まれない場合は「{SLUG_FALLBACK_PREFIX}
                  -xxxx」形式の識別子が自動生成されます（xxxxはランダム）
                </li>
              )}
            </ul>
          </div>
        </div>

        {/* ディレクトリ入力（Filesystem STDIO の場合のみ） */}
        {isFilesystemStdio && (
          <div className="mb-6">
            <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
              アクセスディレクトリ
            </label>
            <input
              type="text"
              value={directoryPath}
              onChange={(e) => setDirectoryPath(e.target.value)}
              placeholder="/home/user/documents"
              className="w-full rounded-lg border border-gray-200 bg-black/[.02] px-4 py-3 text-sm text-gray-900 outline-none dark:border-white/[.08] dark:bg-white/[.03] dark:text-white"
            />
            <p className="mt-1.5 text-xs text-gray-500 dark:text-zinc-500">
              MCPサーバーがアクセスできるディレクトリのパスを指定してください
            </p>
          </div>
        )}

        {/* URL入力（Outline の場合のみ） */}
        {isOutline && (
          <div className="mb-6">
            <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
              サーバーURL
            </label>
            <input
              type="text"
              value={customUrl}
              onChange={(e) => setCustomUrl(e.target.value)}
              placeholder="https://app.getoutline.com/mcp"
              className="w-full rounded-lg border border-gray-200 bg-black/[.02] px-4 py-3 text-sm text-gray-900 outline-none dark:border-white/[.08] dark:bg-white/[.03] dark:text-white"
            />
            <p className="mt-1.5 text-xs text-gray-500 dark:text-zinc-500">
              セルフホストの場合はURLを変更してください（例:
              https://your-domain.com/mcp）
            </p>
          </div>
        )}

        {/* 認証タイプ + 通信方式（カタログ指定・readonly 表示） */}
        <div className="mb-6 grid grid-cols-2 gap-4">
          <div>
            <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
              認証タイプ
            </label>
            <div className="rounded-lg border border-gray-200 bg-[#e8eaed] px-4 py-3 text-sm text-gray-600 dark:border-white/[.08] dark:bg-[#0a0a0a] dark:text-zinc-400">
              {AUTH_TYPE_LABEL[catalog.authType]}
            </div>
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
              通信方式
            </label>
            <div className="rounded-lg border border-gray-200 bg-[#e8eaed] px-4 py-3 text-sm text-gray-600 dark:border-white/[.08] dark:bg-[#0a0a0a] dark:text-zinc-400">
              {TRANSPORT_LABEL[catalog.transportType]}
            </div>
          </div>
        </div>

        {/* OAuthクライアント設定（DCR非対応時のみ表示） */}
        {isOAuth && needsManualOAuthClient && (
          <div className="mb-6 overflow-hidden rounded-lg border border-gray-100 dark:border-white/[.03]">
            <button
              type="button"
              onClick={() => setShowOAuthSettings((prev) => !prev)}
              className="flex w-full items-center justify-between px-4 py-3 text-sm font-medium text-gray-900 transition hover:bg-black/[.02] dark:bg-white/[.04] dark:text-white"
              aria-expanded={showOAuthSettings}
            >
              <span>OAuthクライアント設定</span>
              <ChevronDown
                size={16}
                className={`transition-transform ${showOAuthSettings ? "rotate-180" : ""}`}
              />
            </button>
            {showOAuthSettings && (
              <div className="space-y-4 border-t border-t-gray-100 px-4 py-4 dark:border-t-white/[.03]">
                {needsManualOAuthClient && (
                  <>
                    <p className="text-xs text-gray-500 dark:text-zinc-500">
                      このサーバーはOAuth自動登録に対応していません。サービスの開発者設定画面でOAuthアプリを作成し、Client
                      IDとClient Secretを入力してください。
                    </p>
                    <OAuthCallbackUrlField />
                  </>
                )}
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
                    Client ID
                  </label>
                  <input
                    type="text"
                    value={oauthClientId}
                    onChange={(e) => setOauthClientId(e.target.value)}
                    placeholder="Client IDを入力..."
                    className="w-full rounded-lg border border-gray-200 bg-black/[.02] px-4 py-3 text-sm text-gray-900 outline-none placeholder:text-gray-400 dark:border-white/[.08] dark:bg-white/[.03] dark:text-white"
                  />
                </div>
                <div>
                  <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
                    Client Secret
                  </label>
                  <input
                    type="password"
                    autoComplete="new-password"
                    value={oauthClientSecret}
                    onChange={(e) => setOauthClientSecret(e.target.value)}
                    placeholder="Client Secretを入力（任意）..."
                    className="w-full rounded-lg border border-gray-200 bg-black/[.02] px-4 py-3 text-sm text-gray-900 outline-none placeholder:text-gray-400 dark:border-white/[.08] dark:bg-white/[.03] dark:text-white"
                  />
                </div>
              </div>
            )}
          </div>
        )}

        {/* APIキー入力（API_KEY/BEARER の時のみ） */}
        {needsApiKey && (
          <div className="mb-6 space-y-4">
            {credentialKeys.map((key) => (
              <div key={key}>
                <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
                  {key}
                </label>
                <input
                  type="password"
                  autoComplete="new-password"
                  value={credentials[key] ?? ""}
                  onChange={(e) =>
                    setCredentials((prev) => ({
                      ...prev,
                      [key]: e.target.value,
                    }))
                  }
                  placeholder={`${key}を入力...`}
                  className="w-full rounded-lg border border-gray-200 bg-black/[.02] px-4 py-3 text-sm text-gray-900 outline-none placeholder:text-gray-400 dark:border-white/[.08] dark:bg-white/[.03] dark:text-white"
                />
              </div>
            ))}
          </div>
        )}

        {/* エラー表示 */}
        {error && (
          <div className="mb-4 rounded-lg bg-red-500/10 px-4 py-2.5 text-xs text-red-600 dark:bg-red-400/10 dark:text-red-400">
            {error}
          </div>
        )}

        {/* 区切り線 */}
        <div className="mb-5 border-t border-gray-200 dark:border-white/[.08]" />

        {/* ボタン */}
        <div className="flex justify-end gap-3">
          <button
            type="button"
            onClick={() => {
              if (isOAuth && loading) {
                window.electronAPI.oauth.cancelAuth();
              }
              onClose();
            }}
            className="rounded-lg border border-gray-200 px-5 py-2.5 text-sm font-medium text-gray-600 transition hover:opacity-80 dark:border-white/[.08] dark:text-zinc-400"
          >
            キャンセル
          </button>
          <button
            type="button"
            onClick={() => void handleSubmit()}
            disabled={loading}
            className="rounded-lg bg-gray-900 px-6 py-2.5 text-sm font-medium text-white transition hover:opacity-90 disabled:opacity-50 dark:bg-white dark:text-zinc-900"
          >
            {submitLabel}
          </button>
        </div>
      </div>
    </div>
  );
};
