import type { JSX } from "react";
import { useState, useMemo, useEffect, useCallback } from "react";
import { X, Info } from "lucide-react";
import type { CatalogItem } from "../../types/catalog";
import {
  FILESYSTEM_STDIO_NAME,
  OUTLINE_MCP_NAME,
} from "../../shared/catalog.constants";
import {
  authTypeLabel,
  parseCredentialKeys,
} from "../../shared/catalog.helpers";
import { toSlug } from "../../shared/mcp.slug";
import {
  FALLBACK_SLUG_PLACEHOLDER,
  SLUG_FALLBACK_PREFIX,
} from "../../shared/mcp.constants";
import { DISCOVERY_ERROR_CODE } from "../../shared/oauth/discovery-error-codes";

type AddMcpModalProps = {
  catalog: CatalogItem;
  onClose: () => void;
  onSuccess: (serverName: string) => void;
};

export const AddMcpModal = ({
  catalog,
  onClose,
  onSuccess,
}: AddMcpModalProps): JSX.Element => {
  const credentialKeys: string[] = parseCredentialKeys(catalog.credentialKeys);
  const [serverName, setServerName] = useState(catalog.name);
  const [credentials, setCredentials] = useState<Record<string, string>>(
    Object.fromEntries(credentialKeys.map((key) => [key, ""])),
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showSlugInfo, setShowSlugInfo] = useState(false);
  /** DCR非対応サーバー用: client_id/secret入力フォーム表示フラグ */
  const [needsManualOAuthClient, setNeedsManualOAuthClient] = useState(false);
  const [oauthClientId, setOauthClientId] = useState("");
  const [oauthClientSecret, setOauthClientSecret] = useState("");

  const isFilesystemStdio = catalog.name === FILESYSTEM_STDIO_NAME;
  const isOutline = catalog.name === OUTLINE_MCP_NAME;
  const [directoryPath, setDirectoryPath] = useState("");
  const [customUrl, setCustomUrl] = useState(catalog.url ?? "");

  const slug = useMemo(() => toSlug(serverName), [serverName]);
  const isAutoGeneratedSlug = slug === "";

  const needsApiKey =
    (catalog.authType === "API_KEY" || catalog.authType === "BEARER") &&
    credentialKeys.length > 0;

  const hasRequiredCredentials =
    !needsApiKey ||
    credentialKeys.every((key) => (credentials[key] ?? "").trim() !== "");

  const isOAuth = catalog.authType === "OAUTH";

  // OAuth成功/エラーイベントのリスナー
  const handleOAuthSuccess = useCallback(
    (result: { serverId: number; serverName: string }) => {
      setLoading(false);
      onSuccess(result.serverName);
    },
    [onSuccess],
  );

  const handleOAuthError = useCallback((errorMsg: string) => {
    setLoading(false);
    setError(errorMsg);
    setNeedsManualOAuthClient(false);
  }, []);

  useEffect(() => {
    if (!isOAuth) return;

    const unsubSuccess =
      window.electronAPI.oauth.onOAuthSuccess(handleOAuthSuccess);
    const unsubError = window.electronAPI.oauth.onOAuthError(handleOAuthError);

    return () => {
      unsubSuccess();
      unsubError();
    };
  }, [isOAuth, handleOAuthSuccess, handleOAuthError]);

  const handleSubmit = async (): Promise<void> => {
    if (!serverName.trim()) {
      setError("サーバー名を入力してください");
      return;
    }

    if (!hasRequiredCredentials) {
      setError("すべてのAPIキーを入力してください");
      return;
    }

    if (isFilesystemStdio && !directoryPath.trim()) {
      setError("アクセスディレクトリを入力してください");
      return;
    }

    if (isOutline && !customUrl.trim()) {
      setError("サーバーURLを入力してください");
      return;
    }

    setLoading(true);
    setError(null);

    let resolvedArgs = catalog.args;
    if (isFilesystemStdio) {
      try {
        const parsed: unknown = JSON.parse(catalog.args);
        const baseArgs = Array.isArray(parsed) ? (parsed as string[]) : [];
        resolvedArgs = JSON.stringify([...baseArgs, directoryPath.trim()]);
      } catch {
        setError("引数の解析に失敗しました");
        setLoading(false);
        return;
      }
    }

    // OAuth認証フロー
    if (isOAuth) {
      if (!catalog.url) {
        setError("OAuth認証にはURLが必要です");
        setLoading(false);
        return;
      }

      // DCR非対応で手動入力が必要な場合、入力チェック
      if (needsManualOAuthClient && !oauthClientId.trim()) {
        setError("Client IDを入力してください");
        setLoading(false);
        return;
      }

      try {
        await window.electronAPI.oauth.startAuth({
          catalogId: catalog.id,
          catalogName: serverName,
          description: catalog.description,
          transportType: catalog.transportType,
          command: catalog.command,
          args: resolvedArgs,
          url: catalog.url,
          ...(needsManualOAuthClient && {
            oauthClientId: oauthClientId.trim(),
            oauthClientSecret: oauthClientSecret.trim() || undefined,
          }),
        });
        // ブラウザで認証中 — oauth:success / oauth:error イベントを待つ
      } catch (err) {
        // エラーメッセージからコードを抽出（形式: "[CODE] message"）
        const message =
          err instanceof Error ? err.message : "OAuth認証の開始に失敗しました";
        const codeMatch = message.match(/\[(\w+)]\s/);
        const code = codeMatch?.[1];
        const displayMessage = codeMatch
          ? message.slice((codeMatch.index ?? 0) + codeMatch[0].length)
          : message;

        // DCR非対応エラーの場合、手動入力フォームを表示
        if (code === DISCOVERY_ERROR_CODE.DCR_NOT_SUPPORTED) {
          setNeedsManualOAuthClient(true);
          setError(null);
        } else {
          setNeedsManualOAuthClient(false);
          setError(displayMessage);
        }
        setLoading(false);
      }
      return;
    }

    // 通常フロー（NONE / API_KEY / BEARER）
    try {
      const result = await window.electronAPI.mcp.createFromCatalog({
        catalogId: catalog.id,
        catalogName: serverName,
        description: catalog.description,
        transportType: catalog.transportType,
        command: catalog.command,
        args: resolvedArgs,
        url: isOutline ? customUrl : catalog.url,
        credentialKeys,
        credentials,
        authType: catalog.authType,
      });
      onSuccess(result.serverName);
    } catch {
      setError("MCPサーバーの登録に失敗しました");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ backgroundColor: "rgba(0, 0, 0, 0.5)" }}
    >
      <div
        className="w-full max-w-lg rounded-2xl p-8"
        style={{
          backgroundColor: "var(--bg-card)",
          border: "1px solid var(--border)",
        }}
      >
        {/* タイトル + 閉じるボタン */}
        <div className="mb-1 flex items-start justify-between">
          <h2
            className="text-xl font-bold"
            style={{ color: "var(--text-primary)" }}
          >
            {isOAuth
              ? "OAuth認証"
              : catalog.authType === "NONE"
                ? "MCPサーバーの追加"
                : "APIトークンの設定"}
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-md p-1 transition hover:opacity-70"
            style={{ color: "var(--text-muted)" }}
          >
            <X size={20} />
          </button>
        </div>

        {/* 説明文 */}
        <p className="mb-6 text-sm" style={{ color: "var(--text-muted)" }}>
          {isOAuth
            ? `${catalog.name}に接続するためにブラウザでOAuth認証を行います。`
            : catalog.authType === "NONE"
              ? `${catalog.name}をMCPサーバーとして追加します。`
              : `${catalog.name}に接続するために必要なAPIトークンを設定してください。`}
        </p>

        {/* アイコン + 名前 + 認証バッジ */}
        <div className="mb-6 flex items-center gap-3">
          {catalog.iconPath ? (
            <img
              src={catalog.iconPath}
              alt={catalog.name}
              className="h-10 w-10 rounded-lg"
            />
          ) : (
            <div
              className="flex h-10 w-10 items-center justify-center rounded-lg text-xs"
              style={{
                backgroundColor: "var(--bg-card-hover)",
                color: "var(--text-muted)",
              }}
            >
              MCP
            </div>
          )}
          <div>
            <div
              className="text-base font-semibold"
              style={{ color: "var(--text-primary)" }}
            >
              {catalog.name}
            </div>
            <span
              className="mt-0.5 inline-block rounded-full border px-2.5 py-0.5 text-[11px] font-medium"
              style={{
                borderColor: "var(--border)",
                color: "var(--text-secondary)",
              }}
            >
              {authTypeLabel[catalog.authType]}
            </span>
          </div>
        </div>

        {/* サーバー名 */}
        <div className="mb-2">
          <label
            className="mb-2 block text-sm font-medium"
            style={{ color: "var(--text-primary)" }}
          >
            サーバー名
          </label>
          <input
            type="text"
            value={serverName}
            onChange={(e) => setServerName(e.target.value)}
            className="w-full rounded-lg px-4 py-3 text-sm outline-none"
            style={{
              border: "1px solid var(--border)",
              backgroundColor: "var(--bg-input)",
              color: "var(--text-primary)",
            }}
          />
          <p className="mt-1.5 text-xs" style={{ color: "var(--text-muted)" }}>
            表示されるサーバー名を設定できます（空白や大文字を含むことができます）
          </p>
        </div>

        {/* MCP識別子 */}
        <div
          className="relative mb-6"
          onMouseEnter={() => setShowSlugInfo(true)}
          onMouseLeave={() => setShowSlugInfo(false)}
        >
          <button
            type="button"
            className="flex w-full items-center gap-1.5 rounded-lg px-4 py-3 transition-colors"
            style={{
              backgroundColor: showSlugInfo
                ? "var(--bg-active)"
                : "var(--bg-app)",
              border: "1px solid var(--border-subtle)",
            }}
          >
            <span
              className="text-xs font-medium"
              style={{ color: "var(--text-muted)" }}
            >
              MCPサーバー識別子:
            </span>
            <span
              className="font-mono text-xs"
              style={{ color: "var(--text-secondary)" }}
            >
              {isAutoGeneratedSlug
                ? `${FALLBACK_SLUG_PLACEHOLDER}（自動生成）`
                : slug}
            </span>
            <Info
              size={14}
              className="ml-auto flex-shrink-0"
              style={{ color: "var(--text-subtle)" }}
            />
          </button>
          {/* ツールチップ（ホバーでフェードイン、top-start配置） */}
          <div
            className="pointer-events-none absolute bottom-full left-0 z-10 mb-2 w-80 rounded-lg px-4 py-3 text-xs shadow-lg transition-all duration-150"
            style={{
              backgroundColor: "#111827",
              border: "1px solid #374151",
              opacity: showSlugInfo ? 1 : 0,
              transform: showSlugInfo ? "translateY(0)" : "translateY(4px)",
            }}
          >
            <div className="mb-1.5 font-semibold text-white">
              MCPサーバー識別子の用途
            </div>
            <ul className="list-inside list-disc space-y-1 text-gray-300">
              <li>
                ツール名の接頭辞として使用（例:
                {isAutoGeneratedSlug ? FALLBACK_SLUG_PLACEHOLDER : slug}
                __tool_name）
              </li>
              <li>設定ファイルのキーとして使用（Claude Desktop、Cursor等）</li>
              {isAutoGeneratedSlug && (
                <li>
                  サーバー名に英数字が含まれない場合は「{SLUG_FALLBACK_PREFIX}
                  -xxxx」形式の識別子が自動生成されます（xxxxはランダム）
                </li>
              )}
            </ul>
            {/* 矢印 */}
            <div
              className="absolute top-full left-6 h-0 w-0"
              style={{
                borderLeft: "6px solid transparent",
                borderRight: "6px solid transparent",
                borderTop: "6px solid #111827",
              }}
            />
          </div>
        </div>

        {/* ディレクトリ入力（Filesystem STDIO の場合のみ） */}
        {isFilesystemStdio && (
          <div className="mb-6">
            <label
              className="mb-2 block text-sm font-medium"
              style={{ color: "var(--text-primary)" }}
            >
              アクセスディレクトリ
            </label>
            <input
              type="text"
              value={directoryPath}
              onChange={(e) => setDirectoryPath(e.target.value)}
              placeholder="/home/user/documents"
              className="w-full rounded-lg px-4 py-3 text-sm outline-none"
              style={{
                border: "1px solid var(--border)",
                backgroundColor: "var(--bg-input)",
                color: "var(--text-primary)",
              }}
            />
            <p
              className="mt-1.5 text-xs"
              style={{ color: "var(--text-muted)" }}
            >
              MCPサーバーがアクセスできるディレクトリのパスを指定してください
            </p>
          </div>
        )}

        {/* URL入力（Outline の場合のみ） */}
        {isOutline && (
          <div className="mb-6">
            <label
              className="mb-2 block text-sm font-medium"
              style={{ color: "var(--text-primary)" }}
            >
              サーバーURL
            </label>
            <input
              type="text"
              value={customUrl}
              onChange={(e) => setCustomUrl(e.target.value)}
              placeholder="https://app.getoutline.com/mcp"
              className="w-full rounded-lg px-4 py-3 text-sm outline-none"
              style={{
                border: "1px solid var(--border)",
                backgroundColor: "var(--bg-input)",
                color: "var(--text-primary)",
              }}
            />
            <p
              className="mt-1.5 text-xs"
              style={{ color: "var(--text-muted)" }}
            >
              セルフホストの場合はURLを変更してください（例:
              https://your-domain.com/mcp）
            </p>
          </div>
        )}

        {/* APIキー入力（API_KEY認証の場合のみ） */}
        {needsApiKey && (
          <div className="mb-6 space-y-4">
            {credentialKeys.map((key) => (
              <div key={key}>
                <label
                  className="mb-2 block text-sm font-medium"
                  style={{ color: "var(--text-primary)" }}
                >
                  {key}
                </label>
                <input
                  type="password"
                  autoComplete="new-password"
                  value={credentials[key] ?? ""}
                  onChange={(e) =>
                    setCredentials((prev) => ({
                      ...prev,
                      [key]: e.target.value,
                    }))
                  }
                  placeholder={`${key}を入力...`}
                  className="w-full rounded-lg px-4 py-3 text-sm outline-none"
                  style={{
                    border: "1px solid var(--border)",
                    backgroundColor: "var(--bg-input)",
                    color: "var(--text-primary)",
                  }}
                />
              </div>
            ))}
          </div>
        )}

        {/* OAuthクライアント手動入力（DCR非対応サーバー用） */}
        {isOAuth && needsManualOAuthClient && (
          <div className="mb-6 space-y-4">
            <p className="text-xs" style={{ color: "var(--text-muted)" }}>
              このサーバーはOAuth自動登録に対応していません。サービスの開発者設定画面でOAuthアプリを作成し、Client
              IDとClient Secretを入力してください。
            </p>
            <div>
              <label
                className="mb-2 block text-sm font-medium"
                style={{ color: "var(--text-primary)" }}
              >
                Client ID
              </label>
              <input
                type="text"
                value={oauthClientId}
                onChange={(e) => setOauthClientId(e.target.value)}
                placeholder="Client IDを入力..."
                className="w-full rounded-lg px-4 py-3 text-sm outline-none"
                style={{
                  border: "1px solid var(--border)",
                  backgroundColor: "var(--bg-input)",
                  color: "var(--text-primary)",
                }}
              />
            </div>
            <div>
              <label
                className="mb-2 block text-sm font-medium"
                style={{ color: "var(--text-primary)" }}
              >
                Client Secret
              </label>
              <input
                type="password"
                autoComplete="new-password"
                value={oauthClientSecret}
                onChange={(e) => setOauthClientSecret(e.target.value)}
                placeholder="Client Secretを入力（任意）..."
                className="w-full rounded-lg px-4 py-3 text-sm outline-none"
                style={{
                  border: "1px solid var(--border)",
                  backgroundColor: "var(--bg-input)",
                  color: "var(--text-primary)",
                }}
              />
            </div>
          </div>
        )}

        {/* エラー表示 */}
        {error && (
          <div
            className="mb-4 rounded-lg px-4 py-2.5 text-xs"
            style={{
              backgroundColor: "var(--badge-error-bg)",
              color: "var(--badge-error-text)",
            }}
          >
            {error}
          </div>
        )}

        {/* 区切り線 */}
        <div
          className="mb-5"
          style={{
            borderTopWidth: 1,
            borderTopStyle: "solid",
            borderTopColor: "var(--border)",
          }}
        />

        {/* ボタン */}
        <div className="flex justify-end gap-3">
          <button
            type="button"
            onClick={() => {
              if (isOAuth && loading) {
                window.electronAPI.oauth.cancelAuth();
              }
              onClose();
            }}
            className="rounded-lg px-5 py-2.5 text-sm font-medium transition hover:opacity-80"
            style={{
              border: "1px solid var(--border)",
              color: "var(--text-secondary)",
            }}
          >
            キャンセル
          </button>
          <button
            type="button"
            onClick={() => void handleSubmit()}
            disabled={loading}
            className="rounded-lg px-6 py-2.5 text-sm font-medium transition hover:opacity-90 disabled:opacity-50"
            style={{
              backgroundColor: "var(--text-primary)",
              color: "var(--bg-card)",
            }}
          >
            {loading
              ? isOAuth
                ? "ブラウザで認証中..."
                : "追加中..."
              : isOAuth
                ? "ブラウザで認証"
                : catalog.authType === "NONE"
                  ? "追加"
                  : "認証"}
          </button>
        </div>
      </div>
    </div>
  );
};
