import type { JSX } from "react";
import { useState, useMemo, useEffect, useCallback } from "react";
import { X, Info, ChevronDown, Trash2 } from "lucide-react";
import { toSlug } from "../../shared/mcp.slug";
import {
  FALLBACK_SLUG_PLACEHOLDER,
  SLUG_FALLBACK_PREFIX,
} from "../../shared/mcp.constants";
import {
  DISCOVERY_ERROR_CODE,
  extractOAuthErrorCode,
} from "../../shared/oauth/discovery-error-codes";
import { parseArgsToJson } from "../../shared/parse-args";
import {
  Select,
  SelectTrigger,
  SelectContent,
  SelectItem,
  SelectValue,
} from "./Select";

type AuthMethod = "oauth" | "apikey" | "none";
type TransportType = "STDIO" | "SSE" | "STREAMABLE_HTTP";

type AddRemoteMcpModalProps = {
  onClose: () => void;
  onSuccess: (serverName: string) => void;
};

const AUTH_METHOD_LABEL: Record<AuthMethod, string> = {
  oauth: "OAuth認証",
  apikey: "APIキー認証",
  none: "認証なし",
};

const TRANSPORT_LABEL: Record<TransportType, string> = {
  STDIO: "STDIO",
  STREAMABLE_HTTP: "Streamable HTTP",
  SSE: "SSE",
};

export const AddRemoteMcpModal = ({
  onClose,
  onSuccess,
}: AddRemoteMcpModalProps): JSX.Element => {
  const [serverName, setServerName] = useState("");
  const [url, setUrl] = useState("");
  const [command, setCommand] = useState("");
  const [args, setArgs] = useState("");
  const [transportType, setTransportType] =
    useState<TransportType>("STREAMABLE_HTTP");
  const [authMethod, setAuthMethod] = useState<AuthMethod>("oauth");

  const isStdio = transportType === "STDIO";

  // OAuth
  const [oauthClientId, setOauthClientId] = useState("");
  const [oauthClientSecret, setOauthClientSecret] = useState("");
  const [showOAuthSettings, setShowOAuthSettings] = useState(false);
  const [needsManualOAuthClient, setNeedsManualOAuthClient] = useState(false);

  // APIキー
  const [envVars, setEnvVars] = useState<Record<string, string>>({});
  const [newEnvKey, setNewEnvKey] = useState("");
  const [newEnvValue, setNewEnvValue] = useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showSlugInfo, setShowSlugInfo] = useState(false);

  const slug = useMemo(() => toSlug(serverName), [serverName]);
  const isAutoGeneratedSlug = slug === "";

  // OAuth成功/エラーイベントのリスナー
  const handleOAuthSuccess = useCallback(
    (result: { serverId: number; serverName: string }) => {
      setLoading(false);
      onSuccess(result.serverName);
    },
    [onSuccess],
  );

  const handleOAuthError = useCallback((errorMsg: string) => {
    setLoading(false);
    setError(errorMsg);
    setNeedsManualOAuthClient(false);
  }, []);

  useEffect(() => {
    if (authMethod !== "oauth") return;
    const unsubSuccess =
      window.electronAPI.oauth.onOAuthSuccess(handleOAuthSuccess);
    const unsubError = window.electronAPI.oauth.onOAuthError(handleOAuthError);
    return () => {
      unsubSuccess();
      unsubError();
    };
  }, [authMethod, handleOAuthSuccess, handleOAuthError]);

  useEffect(() => {
    if (needsManualOAuthClient) setShowOAuthSettings(true);
  }, [needsManualOAuthClient]);

  // Escapeキーでモーダルを閉じる
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent): void => {
      if (e.key !== "Escape") return;
      if (authMethod === "oauth" && loading) {
        void window.electronAPI.oauth.cancelAuth();
      }
      onClose();
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [onClose, authMethod, loading]);

  const handleAddEnvVar = (): void => {
    if (newEnvKey.trim() && newEnvValue.trim()) {
      setEnvVars((prev) => ({
        ...prev,
        [newEnvKey.trim()]: newEnvValue.trim(),
      }));
      setNewEnvKey("");
      setNewEnvValue("");
    }
  };

  const handleRemoveEnvVar = (key: string): void => {
    setEnvVars((prev) => {
      const newVars = { ...prev };
      delete newVars[key];
      return newVars;
    });
  };

  const isFormValid = useMemo(() => {
    if (!serverName.trim()) return false;
    if (isStdio) {
      if (!command.trim()) return false;
    } else {
      if (!url.trim()) return false;
    }
    if (authMethod === "apikey" && Object.keys(envVars).length === 0)
      return false;
    if (
      authMethod === "oauth" &&
      needsManualOAuthClient &&
      !oauthClientId.trim()
    )
      return false;
    return true;
  }, [
    serverName,
    url,
    command,
    isStdio,
    authMethod,
    envVars,
    needsManualOAuthClient,
    oauthClientId,
  ]);

  const handleSubmit = async (): Promise<void> => {
    if (!serverName.trim()) {
      setError("サーバー名を入力してください");
      return;
    }
    if (isStdio && !command.trim()) {
      setError("コマンドを入力してください");
      return;
    }
    if (!isStdio && !url.trim()) {
      setError("URLを入力してください");
      return;
    }

    setLoading(true);
    setError(null);

    if (authMethod === "oauth") {
      if (needsManualOAuthClient && !oauthClientId.trim()) {
        setError("Client IDを入力してください");
        setLoading(false);
        return;
      }
      try {
        await window.electronAPI.oauth.startAuth({
          catalogName: serverName.trim(),
          description: "",
          transportType,
          command: null,
          args: "[]",
          url: url.trim(),
          ...(needsManualOAuthClient && {
            oauthClientId: oauthClientId.trim(),
            oauthClientSecret: oauthClientSecret.trim() || undefined,
          }),
        });
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "OAuth認証の開始に失敗しました";
        const { code, displayMessage } = extractOAuthErrorCode(message);
        if (code === DISCOVERY_ERROR_CODE.DCR_NOT_SUPPORTED) {
          setNeedsManualOAuthClient(true);
          setError(null);
        } else {
          setNeedsManualOAuthClient(false);
          setError(displayMessage);
        }
        setLoading(false);
      }
      return;
    }

    // NONE / API_KEY
    try {
      const authType =
        authMethod === "apikey" ? ("API_KEY" as const) : ("NONE" as const);
      const credentials = authMethod === "apikey" ? envVars : {};
      const input = isStdio
        ? {
            serverName: serverName.trim(),
            transportType: "STDIO" as const,
            authType,
            credentials,
            command: command.trim(),
            args: parseArgsToJson(args.trim()),
          }
        : {
            serverName: serverName.trim(),
            transportType,
            authType,
            credentials,
            url: url.trim(),
          };
      const result = await window.electronAPI.mcp.createCustomServer(input);
      onSuccess(result.serverName);
    } catch (err) {
      const message =
        err instanceof Error ? err.message : "MCPサーバーの登録に失敗しました";
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  const submitLabel = loading
    ? authMethod === "oauth"
      ? "ブラウザで認証中..."
      : "作成中..."
    : authMethod === "oauth"
      ? "認証してサーバーを追加"
      : "作成";

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="remote-mcp-modal-title"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
    >
      <div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-[var(--border)] bg-[var(--bg-card)] p-8">
        {/* タイトル + 閉じるボタン */}
        <div className="mb-1 flex items-start justify-between">
          <h2
            id="remote-mcp-modal-title"
            className="text-xl font-bold text-[var(--text-primary)]"
          >
            カスタムMCPサーバーの追加
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="flex min-h-[44px] min-w-[44px] items-center justify-center rounded-md text-[var(--text-muted)] transition hover:opacity-70"
          >
            <X size={20} />
          </button>
        </div>

        <p className="mb-6 text-sm text-[var(--text-muted)]">
          MCPサーバーを追加します。サーバー情報を入力してください。
        </p>

        {/* サーバー名 */}
        <div className="mb-2">
          <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
            サーバー名<span className="text-[var(--badge-error-text)]">*</span>
          </label>
          <input
            type="text"
            value={serverName}
            onChange={(e) => setServerName(e.target.value)}
            placeholder="例: My Custom MCP Server"
            disabled={loading}
            className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-4 py-3 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
          />
          <p className="mt-1.5 text-xs text-[var(--text-muted)]">
            表示されるサーバー名を設定できます（空白や大文字を含むことができます）
          </p>
        </div>

        {/* MCP識別子 */}
        <div
          className="relative mb-6"
          onMouseEnter={() => setShowSlugInfo(true)}
          onMouseLeave={() => setShowSlugInfo(false)}
        >
          <div
            className={`flex w-full items-center gap-1.5 rounded-lg border border-[var(--border-subtle)] px-4 py-3 ${
              showSlugInfo ? "bg-[var(--bg-active)]" : "bg-[var(--bg-app)]"
            }`}
          >
            <span className="text-xs font-medium text-[var(--text-muted)]">
              MCPサーバー識別子:
            </span>
            <span className="font-mono text-xs text-[var(--text-secondary)]">
              {isAutoGeneratedSlug
                ? `${FALLBACK_SLUG_PLACEHOLDER}（自動生成）`
                : slug}
            </span>
            <Info size={14} className="ml-auto text-[var(--text-subtle)]" />
          </div>
          <div
            className={`pointer-events-none absolute bottom-full left-0 z-10 mb-2 w-80 rounded-lg border border-[var(--border)] bg-[var(--bg-card)] px-4 py-3 text-xs shadow-lg transition-all duration-150 ${
              showSlugInfo
                ? "translate-y-0 opacity-100"
                : "translate-y-1 opacity-0"
            }`}
          >
            <div className="mb-1.5 font-semibold text-[var(--text-primary)]">
              MCPサーバー識別子の用途
            </div>
            <ul className="list-inside list-disc space-y-1 text-[var(--text-secondary)]">
              <li>
                ツール名の接頭辞として使用（例:
                {isAutoGeneratedSlug ? FALLBACK_SLUG_PLACEHOLDER : slug}
                __tool_name）
              </li>
              <li>設定ファイルのキーとして使用（Claude Desktop、Cursor等）</li>
              {isAutoGeneratedSlug && (
                <li>
                  サーバー名に英数字が含まれない場合は「{SLUG_FALLBACK_PREFIX}
                  -xxxx」形式の識別子が自動生成されます（xxxxはランダム）
                </li>
              )}
            </ul>
          </div>
        </div>

        {/* URL（リモート時）/ コマンド+引数（STDIO時） */}
        {isStdio ? (
          <div className="mb-6 space-y-4">
            <div>
              <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
                コマンド
                <span className="text-[var(--badge-error-text)]">*</span>
              </label>
              <input
                type="text"
                value={command}
                onChange={(e) => setCommand(e.target.value)}
                placeholder="例: npx, node, python"
                disabled={loading}
                className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-4 py-3 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
              />
            </div>
            <div>
              <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
                引数
              </label>
              <input
                type="text"
                value={args}
                onChange={(e) => setArgs(e.target.value)}
                placeholder="例: -y @modelcontextprotocol/server-filesystem /path/to/dir"
                disabled={loading}
                className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-4 py-3 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
              />
              <p className="mt-1.5 text-xs text-[var(--text-muted)]">
                スペース区切りで引数を入力してください（JSON配列形式も可）
              </p>
            </div>
          </div>
        ) : (
          <div className="mb-6">
            <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
              サーバーURL
              <span className="text-[var(--badge-error-text)]">*</span>
            </label>
            <input
              type="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="例: https://example.com/mcp"
              disabled={loading}
              className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-4 py-3 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
            />
          </div>
        )}

        {/* 認証タイプ + 通信方式 */}
        <div className="mb-6 grid grid-cols-2 gap-4">
          <div>
            <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
              認証タイプ
              <span className="text-[var(--badge-error-text)]">*</span>
            </label>
            <Select
              value={authMethod}
              onValueChange={(v) => {
                setAuthMethod(v as AuthMethod);
                setNeedsManualOAuthClient(false);
                setError(null);
              }}
              disabled={loading}
            >
              <SelectTrigger className="w-full">
                <SelectValue>{AUTH_METHOD_LABEL[authMethod]}</SelectValue>
              </SelectTrigger>
              <SelectContent>
                {!isStdio && <SelectItem value="oauth">OAuth認証</SelectItem>}
                <SelectItem value="apikey">APIキー認証</SelectItem>
                <SelectItem value="none">認証なし</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
              通信方式<span className="text-[var(--badge-error-text)]">*</span>
            </label>
            <Select
              value={transportType}
              onValueChange={(v) => {
                const newType = v as TransportType;
                setTransportType(newType);
                // STDIOではOAuth不可なので認証なしに切り替え
                if (newType === "STDIO" && authMethod === "oauth") {
                  setAuthMethod("none");
                }
                setError(null);
              }}
              disabled={loading}
            >
              <SelectTrigger className="w-full">
                <SelectValue>{TRANSPORT_LABEL[transportType]}</SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="STREAMABLE_HTTP">Streamable HTTP</SelectItem>
                <SelectItem value="SSE">SSE</SelectItem>
                <SelectItem value="STDIO">STDIO</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* OAuth設定（アコーディオン） */}
        {authMethod === "oauth" && (
          <div className="mb-6 overflow-hidden rounded-lg border border-[var(--border-subtle)]">
            <button
              type="button"
              onClick={() => setShowOAuthSettings((prev) => !prev)}
              className="flex w-full items-center justify-between px-4 py-3 text-sm font-medium text-[var(--text-primary)] transition hover:bg-[var(--bg-card-hover)]"
              aria-expanded={showOAuthSettings}
            >
              <span>OAuthクライアント設定</span>
              <ChevronDown
                size={16}
                className={`transition-transform ${showOAuthSettings ? "rotate-180" : ""}`}
              />
            </button>
            {showOAuthSettings && (
              <div className="space-y-4 border-t border-t-[var(--border-subtle)] px-4 py-4">
                {needsManualOAuthClient && (
                  <p className="text-xs text-[var(--text-muted)]">
                    このサーバーはOAuth自動登録に対応していません。サービスの開発者設定画面でOAuthアプリを作成し、Client
                    IDとClient Secretを入力してください。
                  </p>
                )}
                {!needsManualOAuthClient && (
                  <p className="text-xs text-[var(--text-muted)]">
                    手動でOAuth認証を行う場合は、クライアント情報をこちらに入力してください。
                    入力がない場合は自動的にDynamic Client Registration
                    (DCR)を実行します。
                  </p>
                )}
                <div>
                  <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
                    Client ID
                  </label>
                  <input
                    type="text"
                    value={oauthClientId}
                    onChange={(e) => setOauthClientId(e.target.value)}
                    placeholder="Client IDを入力..."
                    disabled={loading}
                    className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-4 py-3 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
                  />
                </div>
                <div>
                  <label className="mb-2 block text-sm font-medium text-[var(--text-primary)]">
                    Client Secret
                  </label>
                  <input
                    type="password"
                    autoComplete="new-password"
                    value={oauthClientSecret}
                    onChange={(e) => setOauthClientSecret(e.target.value)}
                    placeholder="Client Secretを入力（任意）..."
                    disabled={loading}
                    className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-4 py-3 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
                  />
                </div>
              </div>
            )}
          </div>
        )}

        {/* APIキー環境変数入力 */}
        {authMethod === "apikey" && (
          <div className="mb-6 space-y-3">
            <label className="block text-sm font-medium text-[var(--text-primary)]">
              環境変数<span className="text-[var(--badge-error-text)]">*</span>
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={newEnvKey}
                onChange={(e) => setNewEnvKey(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") handleAddEnvVar();
                }}
                placeholder="キー名 (例: Authorization)"
                disabled={loading}
                className="flex-1 rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-3 py-2.5 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
              />
              <input
                type="password"
                autoComplete="new-password"
                value={newEnvValue}
                onChange={(e) => setNewEnvValue(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") handleAddEnvVar();
                }}
                placeholder="値"
                disabled={loading}
                className="flex-1 rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-3 py-2.5 text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)] disabled:opacity-50"
              />
              <button
                type="button"
                onClick={handleAddEnvVar}
                disabled={!newEnvKey.trim() || !newEnvValue.trim() || loading}
                className="rounded-lg bg-[var(--text-primary)] px-4 py-2.5 text-sm font-medium text-[var(--bg-card)] transition hover:opacity-90 disabled:opacity-50"
              >
                追加
              </button>
            </div>

            {Object.entries(envVars).length > 0 && (
              <div className="space-y-2">
                {Object.entries(envVars).map(([key]) => (
                  <div
                    key={key}
                    className="flex items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--bg-app)] px-3 py-2"
                  >
                    <code className="flex-1 font-mono text-sm text-[var(--text-secondary)]">
                      {key}: ****
                    </code>
                    <button
                      type="button"
                      onClick={() => handleRemoveEnvVar(key)}
                      disabled={loading}
                      className="flex min-h-[44px] min-w-[44px] items-center justify-center rounded text-[var(--text-muted)] transition hover:opacity-70 disabled:opacity-50"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                ))}
              </div>
            )}

            {Object.keys(envVars).length === 0 && (
              <p className="text-xs text-[var(--badge-warn-text)]">
                APIキー認証には最低1つの環境変数が必要です
              </p>
            )}
          </div>
        )}

        {/* エラー表示 */}
        {error && (
          <div className="mb-4 rounded-lg bg-[var(--badge-error-bg)] px-4 py-2.5 text-xs text-[var(--badge-error-text)]">
            {error}
          </div>
        )}

        {/* 区切り線 */}
        <div className="mb-5 border-t border-[var(--border)]" />

        {/* ボタン */}
        <div className="flex justify-end gap-3">
          <button
            type="button"
            onClick={() => {
              if (authMethod === "oauth" && loading) {
                void window.electronAPI.oauth.cancelAuth();
              }
              onClose();
            }}
            className="rounded-lg border border-[var(--border)] px-5 py-2.5 text-sm font-medium text-[var(--text-secondary)] transition hover:opacity-80"
          >
            キャンセル
          </button>
          <button
            type="button"
            onClick={() => void handleSubmit()}
            disabled={loading || !isFormValid}
            className="rounded-lg bg-[var(--text-primary)] px-6 py-2.5 text-sm font-medium text-[var(--bg-card)] transition hover:opacity-90 disabled:opacity-50"
          >
            {submitLabel}
          </button>
        </div>
      </div>
    </div>
  );
};
