apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: tenant-console
  labels:
    {{- include "tenant-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: tenant-console
    app.kubernetes.io/component: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
