apiVersion: v1
kind: Service
metadata:
  name: tenant-console
  namespace: tenant-console
  labels:
    {{- include "tenant-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tenant-console
    app.kubernetes.io/component: app
  ports:
    - port: 80
      targetPort: 3200
      name: http
