name: Determine Environment
description: |
  ã‚¤ãƒ™ãƒ³ãƒˆã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆã«åŸºã¥ã„ã¦ãƒ‡ãƒ—ãƒ­ã‚¤ç’°å¢ƒã‚’åˆ¤å®šã—ã¾ã™

  åˆ¤å®šãƒ«ãƒ¼ãƒ«:
  - Pull Request â†’ previewç’°å¢ƒ
  - mainãƒ–ãƒ©ãƒ³ãƒã¸ã®push â†’ stagingç’°å¢ƒ  
  - v*ã‚¿ã‚°ã®ä½œæˆ â†’ productionç’°å¢ƒ
  - æ‰‹å‹•å®Ÿè¡Œ(workflow_dispatch) â†’ é¸æŠžã—ãŸç’°å¢ƒ

outputs:
  environment:
    description: ãƒ‡ãƒ—ãƒ­ã‚¤ç’°å¢ƒï¼ˆpreview/staging/productionï¼‰
    value: ${{ steps.determine.outputs.environment }}
  stage:
    description: ãƒ‡ãƒ—ãƒ­ã‚¤ã‚¹ãƒ†ãƒ¼ã‚¸
    value: ${{ steps.determine.outputs.stage }}
  is_pr:
    description: PRãƒ‡ãƒ—ãƒ­ã‚¤ã‹ã©ã†ã‹ã®ãƒ•ãƒ©ã‚°
    value: ${{ steps.determine.outputs.is_pr }}

runs:
  using: composite
  steps:
    - name: Determine environment
      id: determine
      shell: bash
      run: |
        echo "ðŸ“‹ Event: ${{ github.event_name }}"
        echo "ðŸ”– Ref: ${{ github.ref }}"

        # Pull Request â†’ previewç’°å¢ƒ
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "environment=preview" >> $GITHUB_OUTPUT
          echo "stage=preview" >> $GITHUB_OUTPUT
          echo "is_pr=true" >> $GITHUB_OUTPUT
          echo "ðŸ”µ Pull Request detected â†’ previewç’°å¢ƒ"
          
        # æ‰‹å‹•å®Ÿè¡Œ â†’ é¸æŠžã—ãŸç’°å¢ƒ
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          echo "stage=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          echo "is_pr=false" >> $GITHUB_OUTPUT
          echo "ðŸŸ£ Manual dispatch â†’ ${{ github.event.inputs.environment }}ç’°å¢ƒ"
          
        # v*ã‚¿ã‚° â†’ productionç’°å¢ƒ
        elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          echo "environment=production" >> $GITHUB_OUTPUT
          echo "stage=production" >> $GITHUB_OUTPUT
          echo "is_pr=false" >> $GITHUB_OUTPUT
          echo "ðŸ”´ Version tag detected â†’ productionç’°å¢ƒ"
          
        # ãã®ä»–ï¼ˆmainãƒ–ãƒ©ãƒ³ãƒã¸ã®pushç­‰ï¼‰ â†’ stagingç’°å¢ƒ
        else
          echo "environment=staging" >> $GITHUB_OUTPUT
          echo "stage=staging" >> $GITHUB_OUTPUT
          echo "is_pr=false" >> $GITHUB_OUTPUT
          echo "ðŸŸ¡ Default (main branch push) â†’ stagingç’°å¢ƒ"
        fi
