import { FILESYSTEM_STDIO_NAME } from "../../../shared/catalog.constants";
import type { CatalogSeedData } from "./catalog.repository";

/**
 * Desktop用MCPカタログのシードデータ
 * DEV-1461: 全トランスポート対応MCPの調査・登録
 *
 * 説明文のトーンは Manager 向けシード（packages/scripts の MCP_SERVERS / STDIO_MCP_SERVERS）に合わせる。
 * 並び順: stdio（ローカル）→ Streamable HTTP / SSE（リモート）
 */
export const CATALOG_SEEDS: readonly CatalogSeedData[] = [
  // ========================================
  // stdio MCP（ローカルプロセス）— 表の順
  // ========================================
  {
    name: FILESYSTEM_STDIO_NAME,
    description:
      "ファイルシステム操作 - ローカルファイルの読み書き（開発・テスト用）",
    iconPath: "/logos/services/filesystem.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "Sequential Thinking STDIO",
    description: "段階的思考サーバー - 複雑な問題解決のための段階的推論支援",
    iconPath: "/logos/services/sequential-thinking.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "Serena STDIO",
    description:
      "Serena コード支援 - シンボル検索、ファイル参照、エージェント向け編集補助",
    iconPath: "/logos/services/serena.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@oraios/serena"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "DeepL STDIO",
    description: "DeepL 翻訳サービス",
    iconPath: "/logos/services/deepl.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "deepl-mcp-server"],
    credentialKeys: ["DEEPL_API_KEY"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "Brave Search STDIO",
    description: "Brave Search API統合 - 検索エンジンAPI",
    iconPath: "/logos/services/brave.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@brave/brave-search-mcp-server"],
    credentialKeys: ["BRAVE_API_KEY"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "Chatwork STDIO",
    description:
      "Chatwork API統合 - ルーム・メッセージの参照、送信、通知まわりの操作",
    iconPath: "/logos/services/chatwork.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@chatwork/mcp-server"],
    credentialKeys: ["CHATWORK_API_TOKEN"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "Microsoft Clarity STDIO",
    description: "Microsoft Clarity分析とヒートマップ統合",
    iconPath: "/logos/services/clarity.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@microsoft/clarity-mcp-server"],
    credentialKeys: ["CLARITY_API_TOKEN"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "Kubernetes STDIO",
    description: "Kubernetes API とリソース管理",
    iconPath: "/logos/services/kubernetes.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "kubernetes-mcp-server@latest"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "LINE Bot STDIO",
    description: "LINE Messaging API統合 - Bot からのメッセージ送信・会話操作",
    iconPath: "/logos/services/line.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@line/line-bot-mcp-server"],
    credentialKeys: ["LINE_CHANNEL_ACCESS_TOKEN", "DESTINATION_USER_ID"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "microCMS STDIO",
    description: "microCMS API統合",
    iconPath: "/logos/services/microcms.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "microcms-mcp-server@latest"],
    credentialKeys: ["MICROCMS_API_KEY", "MICROCMS_SERVICE_ID"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "Backlog STDIO",
    description: "Backlog API統合 - 課題、Wiki、ファイル、通知の操作",
    iconPath: "/logos/services/backlog.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "backlog-mcp-server@latest"],
    credentialKeys: ["BACKLOG_DOMAIN", "BACKLOG_API_KEY"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "Salesforce STDIO",
    description:
      "Salesforce MCP - オブジェクト・メタデータの参照と操作（組織認証が前提）",
    iconPath: "/logos/services/salesforce.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@salesforce/mcp@latest"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "Chrome DevTools STDIO",
    description:
      "Chrome DevTools MCP - DOM・コンソール・ネットワーク・パフォーマンスのデバッグ",
    iconPath: "/logos/services/chrome-devtools.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "chrome-devtools-mcp@latest"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "Playwright STDIO",
    description:
      "Playwright MCP - ブラウザ操作、スクリーンショット、フォーム入力、UI検証",
    iconPath: "/logos/services/playwright.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "@playwright/mcp@latest"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "国土交通データプラットフォーム MCP STDIO",
    description:
      "国土交通データプラットフォーム MCP - 地理・オープンデータの検索と取得",
    iconPath: "/logos/services/mlit-geospatial.svg",
    transportType: "STDIO",
    command: "pipx",
    args: ["run", "mlit-dpf-mcp"],
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "Google Analytics MCP",
    description:
      "Google アナリティクス MCP - プロパティ・レポート・指標へのアクセス",
    iconPath: "/logos/services/google-analytics.svg",
    transportType: "STDIO",
    command: "pipx",
    args: ["run", "analytics-mcp"],
    credentialKeys: ["GOOGLE_APPLICATION_CREDENTIALS", "GOOGLE_PROJECT_ID"],
    authType: "API_KEY",
    isOfficial: true,
  },
  {
    name: "Firecrawl MCP",
    description: "Firecrawl ウェブスクレイピング・クローリングサービス",
    iconPath: "/logos/services/firecrawl.svg",
    transportType: "STDIO",
    command: "npx",
    args: ["-y", "firecrawl-mcp"],
    credentialKeys: ["FIRECRAWL_API_KEY"],
    authType: "API_KEY",
    isOfficial: true,
  },

  // ========================================
  // Streamable HTTP / SSE（リモート）— 表の順
  // ========================================
  {
    name: "Context7",
    description:
      "ライブラリドキュメント検索サービス - 最新のドキュメントをリアルタイムで取得",
    iconPath: "/logos/services/context7.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.context7.com/mcp",
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "Figma MCP",
    description:
      "Figma 公式MCPサーバー - デザインファイルの読み取りとコード生成",
    iconPath: "/logos/services/figma.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.figma.com/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Linear MCP",
    description:
      "Linear プロジェクト管理サービス - イシュー、プロジェクト、チーム情報へのアクセス",
    iconPath: "/logos/services/linear.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.linear.app/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Notion MCP",
    description:
      "Notion ワークスペース統合 - ページ、データベース、コメントへのライブアクセス",
    iconPath: "/logos/services/notion.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.notion.com/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Google Maps MCP",
    description:
      "Google Maps Platform MCP - ルート検索、地点情報、距離・移動時間の取得",
    iconPath: "/logos/services/google-maps.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.googleapis.com/v1alpha/maps:streamableHttp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "GitHub MCP",
    description:
      "GitHub 公式MCPサーバー - リポジトリ、イシュー、PR、ワークフローの管理",
    iconPath: "/logos/services/github_black.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://api.githubcopilot.com/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "GitLab MCP",
    description: "GitLab 公式MCPサーバー - リポジトリ、イシュー、MR の操作",
    iconPath: "/logos/services/gitlab.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://gitlab.com/api/v4/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Slack MCP",
    description: "Slack MCP - チャンネル・スレッド・メッセージの参照と投稿",
    iconPath: "/logos/services/slack.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.slack.com/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Money Forward MCP",
    description:
      "マネーフォワード クラウド会計 MCP - 取引・口座・帳票など会計データへのアクセス",
    iconPath: "/logos/services/moneyforward.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.moneyforward.com/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Freee MCP",
    description: "freee MCP - 会計・人事労務データの参照と操作",
    iconPath: "/logos/services/freee.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.freee.co.jp/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Atlassian MCP",
    description: "Atlassian 公式MCPサーバー - Jira、Confluenceとの統合アクセス",
    iconPath: "/logos/services/atlassian.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.atlassian.com/v1/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Asana MCP",
    description: "Asana MCP - プロジェクト、タスク、コメントの管理",
    iconPath: "/logos/services/asana.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.asana.com/v2/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Neon MCP",
    description:
      "Neon PostgreSQL データベースサービス - データベース管理とAI統合",
    iconPath: "/logos/services/neon.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.neon.tech/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Supabase MCP",
    description:
      "Supabase プロジェクト管理 - データベース、認証、ストレージへのアクセス",
    iconPath: "/logos/services/supabase.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.supabase.com/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "HubSpot MCP",
    description:
      "HubSpot CRM MCP - コンタクト、会社、取引、マーケティング活動の管理",
    iconPath: "/logos/services/hubspot.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.hubspot.com",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Box MCP",
    description:
      "Box MCP - ファイル検索、メタデータ参照、共有・コラボレーション",
    iconPath: "/logos/services/box.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.box.com",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Attio MCP",
    description: "Attio CRM MCP - 人物、会社、リスト、パイプラインの管理",
    iconPath: "/logos/services/attio.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://mcp.attio.com/mcp",
    credentialKeys: [],
    authType: "OAUTH",
    isOfficial: true,
  },
  {
    name: "Jグランツ MCP",
    description:
      "jGrants MCP - 補助金電子申請（デジタル庁）向けのデータ参照・操作（ローカルサーバー接続）",
    iconPath: "/logos/services/jgrants.svg",
    transportType: "STREAMABLE_HTTP",
    url: "http://127.0.0.1:8000/mcp",
    credentialKeys: [],
    authType: "NONE",
    isOfficial: true,
  },
  {
    name: "Outline MCP",
    description:
      "Outline ナレッジベース MCP - コレクション・ドキュメントの検索と参照",
    iconPath: "/logos/services/outline.svg",
    transportType: "STREAMABLE_HTTP",
    url: "https://app.getoutline.com/mcp",
    credentialKeys: ["OUTLINE_API_KEY"],
    authType: "BEARER",
    isOfficial: true,
  },
];
