import type { JSX } from "react";
import { useState, useEffect, useMemo, useRef } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Check, Plus, Search } from "lucide-react";
import type {
  McpServerItem,
  McpConnectionItem,
  ConnectionToolsResult,
} from "../../main/types";
import { toast } from "../_components/Toast";
import { ToggleSwitch } from "../_components/ToggleSwitch";
import { toSlug } from "../../shared/mcp.slug";
import {
  FALLBACK_SLUG_PLACEHOLDER,
  VIRTUAL_SERVER_MAX_CONNECTIONS,
} from "../../shared/mcp.constants";

/** 仮想MCP化の対象として表示する単一接続コネクタ */
type SelectableConnector = {
  serverId: number;
  serverName: string;
  connection: McpConnectionItem;
};

/**
 * 既存の McpServer 一覧から「コネクタとして選択可能な単独コネクタ」を平坦化して取り出す。
 * 仮想MCP（serverType === "CUSTOM"）は再ネスト禁止で除外し、無効化されたものも除外する。
 * 1接続の仮想MCPもこのフィルタで弾かれる（DEV-1625）。
 */
const flattenSelectableConnectors = (
  servers: McpServerItem[],
): SelectableConnector[] =>
  servers
    .filter((server) => server.serverType === "OFFICIAL" && server.isEnabled)
    .flatMap((server) => {
      // 公式コネクタは1接続前提だが、複数接続の防御として最初の接続が有効な場合のみ採用する
      const connection = server.connections[0];
      if (!connection) return [];
      // 接続自体が無効化されている場合は除外
      // （サーバーが有効でも接続が無効な場合があり、サービス層でも !source.isEnabled で弾かれる）
      if (!connection.isEnabled) return [];
      return [
        {
          serverId: server.id,
          serverName: server.name,
          connection,
        },
      ];
    });

export const ConnectorManual = (): JSX.Element => {
  const navigate = useNavigate();

  // 選択可能なコネクタ一覧（コネクト画面で追加済みの単一接続コネクタから派生）
  const [connectors, setConnectors] = useState<SelectableConnector[]>([]);
  const [loadingConnectors, setLoadingConnectors] = useState(true);

  const [serverName, setServerName] = useState("");
  const [description, setDescription] = useState("");
  const [selectedConnectionIds, setSelectedConnectionIds] = useState<number[]>(
    [],
  );

  // ツール一覧（connectionId → tools[]）と取得状態
  const [toolsByConnectionId, setToolsByConnectionId] = useState<
    Record<number, ConnectionToolsResult["tools"]>
  >({});
  const [loadingToolsFor, setLoadingToolsFor] = useState<Set<number>>(
    () => new Set(),
  );
  // ツール一覧フェッチに失敗した接続ID集合。インラインの再試行ボタン表示に使用
  const [failedToolLoads, setFailedToolLoads] = useState<Set<number>>(
    () => new Set(),
  );
  // connectionId → toolName → 公開可否（true=公開）
  const [allowedMap, setAllowedMap] = useState<
    Record<number, Record<string, boolean>>
  >({});
  // connectionId → ツール検索クエリ（コネクタごとに独立）
  const [toolQueries, setToolQueries] = useState<Record<number, string>>({});

  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // 進行中のツール一覧フェッチを同期的に追跡し、二重フェッチを防ぐ
  // （loadingToolsFor は state のため setState 反映前に再呼び出しされると素通りする）
  const inflightLoadsRef = useRef<Set<number>>(new Set());

  useEffect(() => {
    window.electronAPI.mcp
      .getAll()
      .then((servers) => {
        setConnectors(flattenSelectableConnectors(servers));
      })
      .catch(() => {
        setConnectors([]);
        toast.error("コネクタの読み込みに失敗しました");
      })
      .finally(() => setLoadingConnectors(false));
  }, []);

  const slug = useMemo(() => toSlug(serverName), [serverName]);
  const isAutoGeneratedSlug = slug === "";

  const connectorByConnectionId = useMemo(() => {
    const map = new Map<number, SelectableConnector>();
    for (const connector of connectors) {
      map.set(connector.connection.id, connector);
    }
    return map;
  }, [connectors]);

  const selectedConnectors = useMemo(
    () =>
      selectedConnectionIds
        .map((id) => connectorByConnectionId.get(id))
        .filter((c): c is SelectableConnector => c !== undefined),
    [selectedConnectionIds, connectorByConnectionId],
  );

  /**
   * 選択コネクタのツール一覧を取得して内部キャッシュ・isAllowed初期値を埋める。
   * 既に取得済みなら no-op（再取得すると編集中のチェックが消えるため）。
   */
  const loadToolsForConnection = async (
    connectionId: number,
  ): Promise<void> => {
    // 既にツール一覧をロード済み、または別フェッチが進行中なら何もしない
    if (toolsByConnectionId[connectionId] !== undefined) return;
    if (inflightLoadsRef.current.has(connectionId)) return;
    inflightLoadsRef.current.add(connectionId);

    setLoadingToolsFor((prev) => {
      const next = new Set(prev);
      next.add(connectionId);
      return next;
    });
    // 再試行のため、既存の失敗フラグはクリアする
    setFailedToolLoads((prev) => {
      if (!prev.has(connectionId)) return prev;
      const next = new Set(prev);
      next.delete(connectionId);
      return next;
    });
    try {
      const result = await window.electronAPI.mcp.getToolsForConnections({
        connectionIds: [connectionId],
      });
      const item = result.items[0];
      if (!item) return;
      setToolsByConnectionId((prev) => ({
        ...prev,
        [connectionId]: item.tools,
      }));
      // 要件「ツール選択のデフォルト値としてコネクタで設定した値を利用する」
      // → 元コネクタの isAllowed をそのまま初期値にする
      setAllowedMap((prev) => ({
        ...prev,
        [connectionId]: Object.fromEntries(
          item.tools.map((tool) => [tool.name, tool.isAllowed]),
        ),
      }));
    } catch (e) {
      const message =
        e instanceof Error ? e.message : "ツール一覧の取得に失敗しました";
      toast.error(message);
      setFailedToolLoads((prev) => {
        const next = new Set(prev);
        next.add(connectionId);
        return next;
      });
    } finally {
      inflightLoadsRef.current.delete(connectionId);
      setLoadingToolsFor((prev) => {
        const next = new Set(prev);
        next.delete(connectionId);
        return next;
      });
    }
  };

  const toggleConnector = (connectionId: number): void => {
    if (selectedConnectionIds.includes(connectionId)) {
      setSelectedConnectionIds((prev) =>
        prev.filter((x) => x !== connectionId),
      );
      // 選択解除時に当該接続のロード/失敗状態もクリアする
      // （残したままだと canSubmit が永続的に false になり再送信できなくなる）
      setFailedToolLoads((prev) => {
        if (!prev.has(connectionId)) return prev;
        const next = new Set(prev);
        next.delete(connectionId);
        return next;
      });
      setLoadingToolsFor((prev) => {
        if (!prev.has(connectionId)) return prev;
        const next = new Set(prev);
        next.delete(connectionId);
        return next;
      });
      return;
    }
    if (selectedConnectionIds.length >= VIRTUAL_SERVER_MAX_CONNECTIONS) {
      toast.error(
        `接続は最大${String(VIRTUAL_SERVER_MAX_CONNECTIONS)}件までです`,
      );
      return;
    }
    setSelectedConnectionIds((prev) => [...prev, connectionId]);
    void loadToolsForConnection(connectionId);
  };

  /** ツールごとの公開可否を直接セット（ToggleSwitch から boolean を受け取る） */
  const setToolAllowed = (
    connectionId: number,
    toolName: string,
    isAllowed: boolean,
  ): void => {
    setAllowedMap((prev) => {
      const current = prev[connectionId] ?? {};
      return {
        ...prev,
        [connectionId]: {
          ...current,
          [toolName]: isAllowed,
        },
      };
    });
  };

  // ツール一覧フェッチ中は allowedMap が未初期化のため送信を抑止する
  // （空の allowedToolNames=[] が渡るとサービス層で全ツール非公開扱いになる）
  // 取得失敗中も同様に抑止し、ユーザーに再試行を促す
  // 選択中の接続のみを評価対象とする（解除済みコネクタの過去の失敗で永続ブロックされないよう）
  const canSubmit =
    serverName.trim() !== "" &&
    selectedConnectionIds.length > 0 &&
    selectedConnectionIds.every((id) => !loadingToolsFor.has(id)) &&
    selectedConnectionIds.every((id) => !failedToolLoads.has(id)) &&
    !submitting;

  const handleSubmit = async (): Promise<void> => {
    if (!canSubmit) return;
    setSubmitting(true);
    setError(null);
    try {
      const result = await window.electronAPI.mcp.createVirtualServer({
        name: serverName.trim(),
        description: description.trim(),
        connections: selectedConnectionIds.map((connectionId) => {
          const allowed = allowedMap[connectionId] ?? {};
          // 公開する（isAllowed=true）ツール名一覧を構築
          const allowedToolNames = Object.entries(allowed)
            .filter(([, isAllowed]) => isAllowed)
            .map(([name]) => name);
          // allowedMap に当該 connectionId のキーが存在すれば「ツール一覧をフェッチ済みで
          // ユーザーが編集可能だった」と判断し、空配列もそのまま渡してサービス層で
          // 「全ツール非公開」として扱わせる。キー未登録（=フェッチ未完了の保険的ケース）
          // のみ undefined を渡し、サービス側で元コネクタの isAllowed を継承させる。
          const hasEditedTools = connectionId in allowedMap;
          return {
            connectionId,
            allowedToolNames: hasEditedTools ? allowedToolNames : undefined,
          };
        }),
      });
      toast.success(`${result.serverName}を作成しました`);
      navigate("/tools");
    } catch (e) {
      const message =
        e instanceof Error ? e.message : "仮想MCPの作成に失敗しました";
      setError(message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="space-y-6 p-6">
      <Link
        to="/tools"
        className="inline-flex items-center gap-1 text-sm text-[var(--text-muted)] hover:opacity-80"
      >
        <ArrowLeft size={14} /> コネクト
      </Link>

      <div>
        <h1 className="text-lg font-semibold text-[var(--text-primary)]">
          マニュアル作成
        </h1>
        <p className="mt-1 text-xs text-[var(--text-muted)]">
          追加済みのコネクタを束ねた仮想MCPサーバーを作成します
        </p>
      </div>

      <div className="rounded-xl border border-[var(--border)] bg-[var(--bg-card)] p-5 shadow-[var(--shadow-card)]">
        {/* サーバー名 */}
        <div className="mb-5">
          <label className="mb-1 block text-xs text-[var(--text-muted)]">
            サーバー名
          </label>
          <input
            type="text"
            value={serverName}
            onChange={(e) => setServerName(e.target.value)}
            placeholder="例: 週次レポート用コネクタ"
            className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-3 py-2.5 text-sm text-[var(--text-primary)] outline-none"
          />
          <p className="mt-1.5 text-[10px] text-[var(--text-muted)]">
            MCP識別子:{" "}
            <span className="font-mono text-[var(--text-secondary)]">
              {isAutoGeneratedSlug
                ? `${FALLBACK_SLUG_PLACEHOLDER}（自動生成）`
                : slug}
            </span>
            <span className="ml-1 text-[var(--text-subtle)]">
              {isAutoGeneratedSlug
                ? `※サーバー名に英数字が含まれない場合は「${FALLBACK_SLUG_PLACEHOLDER}」形式の識別子が自動生成されます`
                : "※同名サーバーが既に存在する場合は自動で番号が付与されます"}
            </span>
          </p>
        </div>

        {/* 説明 */}
        <div className="mb-5">
          <label className="mb-1 block text-xs text-[var(--text-muted)]">
            説明（任意）
          </label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            rows={2}
            placeholder="この仮想MCPサーバーの用途を記述..."
            className="w-full resize-none rounded-lg border border-[var(--border)] bg-[var(--bg-input)] px-3 py-2.5 text-sm text-[var(--text-primary)] outline-none"
          />
        </div>

        {/* コネクタ選択 */}
        <div className="mb-5 border-t border-t-[var(--border)] pt-4">
          <label className="mb-2 block text-xs text-[var(--text-muted)]">
            束ねるコネクタを選択（{selectedConnectionIds.length} /{" "}
            {String(VIRTUAL_SERVER_MAX_CONNECTIONS)}）
          </label>
          {loadingConnectors ? (
            <div className="py-6 text-center text-xs text-[var(--text-subtle)]">
              読み込み中...
            </div>
          ) : connectors.length === 0 ? (
            <div className="rounded-lg bg-[var(--bg-card-hover)] p-4 text-center text-xs text-[var(--text-subtle)]">
              選択可能なコネクタがありません。
              <br />
              <Link
                to="/tools"
                className="text-[var(--text-secondary)] underline hover:opacity-80"
              >
                コネクト画面
              </Link>
              からMCPを追加してください。
            </div>
          ) : (
            <div className="grid grid-cols-2 gap-2 lg:grid-cols-3">
              {connectors.map((connector) => {
                const isSelected = selectedConnectionIds.includes(
                  connector.connection.id,
                );
                const iconPath = connector.connection.catalog?.iconPath;
                return (
                  <button
                    key={connector.connection.id}
                    type="button"
                    onClick={() => toggleConnector(connector.connection.id)}
                    className={`flex min-h-[44px] items-center gap-2 rounded-lg border px-3 py-2 text-left text-xs transition-colors ${
                      isSelected
                        ? "border-emerald-400/30 bg-[var(--bg-active)] text-[var(--text-primary)]"
                        : "border-transparent bg-[var(--bg-card-hover)] text-[var(--text-secondary)]"
                    }`}
                  >
                    {iconPath ? (
                      <img
                        src={iconPath}
                        alt={connector.serverName}
                        className="h-4 w-4 shrink-0 rounded"
                      />
                    ) : (
                      <div className="flex h-4 w-4 shrink-0 items-center justify-center rounded bg-[var(--bg-input)] text-[7px] text-[var(--text-subtle)]">
                        MCP
                      </div>
                    )}
                    <span className="flex-1 truncate">
                      {connector.serverName}
                    </span>
                    {isSelected && (
                      <Check
                        size={12}
                        className="shrink-0 text-[var(--badge-success-text)]"
                      />
                    )}
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {/* ツール選択エリア（コネクト UI の「提供ツール」と同じカード形式） */}
        {selectedConnectors.length > 0 && (
          <div className="mb-5 border-t border-t-[var(--border)] pt-4">
            <label className="mb-3 block text-xs text-[var(--text-muted)]">
              ツール設定
            </label>
            <div className="space-y-3">
              {selectedConnectors.map((connector) => {
                const connectionId = connector.connection.id;
                const tools = toolsByConnectionId[connectionId] ?? [];
                const perTool = allowedMap[connectionId] ?? {};
                const allowedCount = tools.filter(
                  (tool) => perTool[tool.name],
                ).length;
                const isLoading = loadingToolsFor.has(connectionId);
                const hasFailed = failedToolLoads.has(connectionId);
                const iconPath = connector.connection.catalog?.iconPath;
                const query = toolQueries[connectionId] ?? "";
                const lowerQuery = query.trim().toLowerCase();
                const filteredTools =
                  lowerQuery === ""
                    ? tools
                    : tools.filter(
                        (tool) =>
                          tool.name.toLowerCase().includes(lowerQuery) ||
                          (tool.description ?? "")
                            .toLowerCase()
                            .includes(lowerQuery),
                      );
                return (
                  <div
                    key={connectionId}
                    className="rounded-lg border border-[var(--border-subtle)] bg-[var(--bg-card-hover)] p-3"
                  >
                    {/* コネクタヘッダー */}
                    <div className="mb-2 flex items-center gap-2">
                      {iconPath ? (
                        <img
                          src={iconPath}
                          alt={connector.serverName}
                          className="h-4 w-4 rounded"
                        />
                      ) : (
                        <div className="flex h-4 w-4 items-center justify-center rounded bg-[var(--bg-input)] text-[7px] text-[var(--text-subtle)]">
                          MCP
                        </div>
                      )}
                      <h3 className="text-xs font-medium text-[var(--text-primary)]">
                        {connector.serverName}
                      </h3>
                      <span className="ml-auto text-[10px] text-[var(--text-subtle)]">
                        {allowedCount} / {tools.length} ツール選択中
                      </span>
                    </div>

                    {/* 検索バー（コネクト UI と同形式、ツールが多い場合のみ表示） */}
                    {tools.length > 5 && (
                      <div className="relative mb-2">
                        <Search
                          size={12}
                          className="absolute top-1/2 left-2.5 -translate-y-1/2 text-[var(--text-subtle)]"
                        />
                        <input
                          type="text"
                          placeholder="ツールを検索..."
                          value={query}
                          onChange={(e) =>
                            setToolQueries((prev) => ({
                              ...prev,
                              [connectionId]: e.target.value,
                            }))
                          }
                          className="w-full rounded-lg border border-[var(--border)] bg-[var(--bg-input)] py-1.5 pr-2 pl-8 text-xs text-[var(--text-primary)] outline-none placeholder:text-[var(--text-subtle)]"
                        />
                      </div>
                    )}

                    {/* ツール一覧（カード + ToggleSwitch） */}
                    {isLoading ? (
                      <p className="py-3 text-center text-[10px] text-[var(--text-subtle)]">
                        ツール一覧を取得中...
                      </p>
                    ) : hasFailed ? (
                      <div className="flex items-center justify-center gap-2 py-3">
                        <p className="text-[10px] text-[var(--badge-error-text)]">
                          ツール一覧の取得に失敗しました
                        </p>
                        <button
                          type="button"
                          onClick={() =>
                            void loadToolsForConnection(connectionId)
                          }
                          className="inline-flex min-h-[44px] items-center rounded border border-[var(--border)] px-2 py-1 text-[10px] text-[var(--text-secondary)] transition-colors hover:opacity-80"
                        >
                          再試行
                        </button>
                      </div>
                    ) : tools.length === 0 ? (
                      <p className="py-3 text-center text-[10px] text-[var(--text-subtle)]">
                        このコネクタにはツールがありません
                      </p>
                    ) : filteredTools.length === 0 ? (
                      <p className="py-3 text-center text-[10px] text-[var(--text-subtle)]">
                        条件に一致するツールが見つかりません
                      </p>
                    ) : (
                      <div className="max-h-64 space-y-1 overflow-y-auto pr-1">
                        {filteredTools.map((tool) => {
                          const isOn = perTool[tool.name] ?? false;
                          return (
                            <div
                              key={tool.name}
                              className="flex items-center justify-between gap-3 rounded-lg border border-[var(--border-subtle)] bg-[var(--bg-input)] px-2.5 py-2"
                            >
                              <div className="min-w-0 flex-1">
                                <div className="truncate font-mono text-xs font-medium text-[var(--text-primary)]">
                                  {tool.name}
                                </div>
                                {tool.description && (
                                  <div className="mt-0.5 line-clamp-1 text-[10px] text-[var(--text-muted)]">
                                    {tool.description}
                                  </div>
                                )}
                              </div>
                              <ToggleSwitch
                                checked={isOn}
                                onChange={(v) =>
                                  setToolAllowed(connectionId, tool.name, v)
                                }
                              />
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* エラー表示 */}
        {error && (
          <div className="mb-4 rounded-lg bg-[var(--badge-error-bg)] px-4 py-2.5 text-xs text-[var(--badge-error-text)]">
            {error}
          </div>
        )}

        {/* ボタン群 */}
        <div className="flex items-center justify-end gap-3 border-t border-t-[var(--border)] pt-4">
          <Link
            to="/tools"
            className="inline-flex min-h-[44px] items-center rounded-lg border border-[var(--border)] px-4 py-2 text-xs text-[var(--text-muted)] transition-colors hover:opacity-80"
          >
            キャンセル
          </Link>
          <button
            type="button"
            onClick={() => void handleSubmit()}
            disabled={!canSubmit}
            className="flex min-h-[44px] items-center gap-1.5 rounded-lg bg-[var(--btn-primary-bg)] px-4 py-2 text-xs font-medium text-[var(--btn-primary-text)] transition-colors hover:opacity-90 disabled:opacity-50"
          >
            <Plus size={14} />
            {submitting ? "作成中..." : "仮想MCPを作成"}
          </button>
        </div>
      </div>
    </div>
  );
};
