name: Deploy to Vercel
description: ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã‚’Vercelã«ãƒ‡ãƒ—ãƒ­ã‚¤ã—ã¾ã™ã€‚ç’°å¢ƒåˆ¥ã®è¨­å®šï¼ˆpreview/staging/productionï¼‰ã«å¯¾å¿œ

inputs:
  environment:
    description: ãƒ‡ãƒ—ãƒ­ã‚¤ç’°å¢ƒï¼ˆpreview/staging/productionï¼‰
    required: true
  vercel_token:
    description: Vercel APIãƒˆãƒ¼ã‚¯ãƒ³
    required: true
  database_url:
    description: ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹æŽ¥ç¶šURL
    required: true
  api_url:
    description: ãƒ‘ãƒ–ãƒªãƒƒã‚¯API URL
    required: true

outputs:
  deployment_url:
    description: ãƒ‡ãƒ—ãƒ­ã‚¤å…ˆURL
    value: ${{ steps.deploy.outputs.url }}

runs:
  using: composite
  steps:
    - name: ðŸ”§ Install Vercel CLI
      shell: bash
      run: |
        if ! command -v vercel &> /dev/null; then
          npm install --global vercel@latest
        fi

    - name: ðŸš€ Deploy to Vercel
      id: deploy
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.vercel_token }}
        DATABASE_URL: ${{ inputs.database_url }}
        NEXT_PUBLIC_API_URL: ${{ inputs.api_url }}
      run: |
        echo "Deploying to ${{ inputs.environment }} environment..."

        if [[ "${{ inputs.environment }}" == "production" ]]; then
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          vercel build --prod --token=$VERCEL_TOKEN
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN)
        else
          vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          vercel build --token=$VERCEL_TOKEN
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)
        fi

        echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
        echo "âœ… Deployed to: $DEPLOYMENT_URL"
