name: Deploy to Vercel
description: ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã‚’Vercelã«ãƒ‡ãƒ—ãƒ­ã‚¤ã—ã¾ã™ã€‚ç’°å¢ƒåˆ¥ã®è¨­å®šï¼ˆpreview/staging/productionï¼‰ã«å¯¾å¿œ

inputs:
  environment:
    description: ãƒ‡ãƒ—ãƒ­ã‚¤ç’°å¢ƒï¼ˆpreview/staging/productionï¼‰
    required: true
  vercel_token:
    description: Vercel APIãƒˆãƒ¼ã‚¯ãƒ³
    required: true
  database_url:
    description: ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹æŽ¥ç¶šURL
    required: true
  api_url:
    description: ãƒ‘ãƒ–ãƒªãƒƒã‚¯API URL
    required: true

outputs:
  deployment_url:
    description: ãƒ‡ãƒ—ãƒ­ã‚¤å…ˆURL
    value: ${{ steps.deploy.outputs.url }}

runs:
  using: composite
  steps:
    - name: ðŸ”§ Install Vercel CLI
      shell: bash
      run: |
        if ! command -v vercel &> /dev/null; then
          npm install --global vercel@latest
        fi

    - name: ðŸš€ Deploy to Vercel
      id: deploy
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.vercel_token }}
        DATABASE_URL: ${{ inputs.database_url }}
        NEXT_PUBLIC_API_URL: ${{ inputs.api_url }}
      run: |
        echo "Deploying to ${{ inputs.environment }} environment..."
        
        # ç’°å¢ƒå¤‰æ•°ã®ç¢ºèª
        if [ -z "$VERCEL_ORG_ID" ] || [ -z "$VERCEL_PROJECT_ID" ]; then
          echo "Error: VERCEL_ORG_ID or VERCEL_PROJECT_ID is not set"
          echo "Please ensure these are set in the GitHub workflow"
          exit 1
        fi

        # Vercelå´ã§ãƒ“ãƒ«ãƒ‰ã‚’å®Ÿè¡Œã™ã‚‹ã‚ˆã†ã«ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã‚’ç›´æŽ¥ãƒ‡ãƒ—ãƒ­ã‚¤
        if [[ "${{ inputs.environment }}" == "production" ]]; then
          echo "Deploying to production environment..."
          DEPLOYMENT_URL=$(vercel deploy --prod --token=$VERCEL_TOKEN)
        elif [[ "${{ inputs.environment }}" == "staging" ]]; then
          echo "Deploying to staging environment..."
          # Pro/Enterpriseãƒ—ãƒ©ãƒ³ã®ã‚«ã‚¹ã‚¿ãƒ ç’°å¢ƒã¸ãƒ‡ãƒ—ãƒ­ã‚¤
          # --target ã‚ªãƒ—ã‚·ãƒ§ãƒ³ã§ã‚«ã‚¹ã‚¿ãƒ ç’°å¢ƒã‚’æŒ‡å®š
          DEPLOYMENT_URL=$(vercel deploy --target=staging --token=$VERCEL_TOKEN)
        else
          echo "Deploying to preview environment..."
          DEPLOYMENT_URL=$(vercel deploy --token=$VERCEL_TOKEN)
        fi

        echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
        echo "âœ… Deployed to: $DEPLOYMENT_URL"
