name: Deploy to GCE
description: ProxyServerã‚’Google Compute Engineï¼ˆæœ¬ç•ªç’°å¢ƒï¼‰ã«ãƒ‡ãƒ—ãƒ­ã‚¤ã—ã¾ã™

inputs:
  gcp_credentials:
    description: GCPã‚µãƒ¼ãƒ“ã‚¹ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã®èªè¨¼JSONï¼ˆæœ¬ç•ªç’°å¢ƒç”¨ï¼‰
    required: true
  instance_name:
    description: GCEã‚¤ãƒ³ã‚¹ã‚¿ãƒ³ã‚¹åï¼ˆæœ¬ç•ªç’°å¢ƒç”¨ï¼‰
    required: true
  zone:
    description: GCEã‚¾ãƒ¼ãƒ³
    required: true
  project_id:
    description: GCPãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆID
    required: true

runs:
  using: composite
  steps:
    - name: ðŸ”‘ Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: â˜ï¸ Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: ðŸ“¦ Build packages for GCE
      shell: bash
      run: |
        echo "Building packages for GCE deployment..."
        pnpm run --filter @tumiki/tsup-config build
        pnpm run --filter @tumiki/db build

    - name: ðŸš€ Deploy to GCE
      shell: bash
      run: |
        echo "Deploying to GCE instance: ${{ inputs.instance_name }}"

        # Create environment file
        cat > .env.deploy << EOF
        NODE_ENV=production
        EOF

        # Run deployment
        INSTANCE_NAME="${{ inputs.instance_name }}" \
        ZONE="${{ inputs.zone }}" \
        PROJECT_ID="${{ inputs.project_id }}" \
        DEPLOY_STAGE="production" \
        bash scripts/deploy-ci.sh

        # Cleanup
        rm -f .env.deploy
