# InfisicalSecret CRD
# Infisical Kubernetes Operator が監視し、Infisical → k8s Secret へ自動同期する
# 同期されるシークレット:
#   - LICENSE_PUBLIC_KEY: ライセンス JWT 検証用 RS256 公開鍵
#   - AI_GATEWAY_API_KEY: Vercel AI Gateway API キー
#   - KEYCLOAK_ISSUER: Keycloak issuer
#   - KEYCLOAK_ALLOWED_AUDIENCES: Keycloak audience 検証対象（本番必須）
#   - KEYCLOAK_SKIP_AUDIENCE_CHECK: audience 検証スキップ（開発・テスト用途のみ）
#   - DYNAMIC_SEARCH_MODEL: 使用モデル名（任意）
#   - DYNAMIC_SEARCH_EMBEDDING_MODEL: 動的ツール検索 embedding モデル名（任意）
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tumiki-cloud-api-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tumiki-cloud-api.labels" . | nindent 4 }}
spec:
  hostAPI: {{ .Values.infisical.hostAPI }}
  resyncInterval: {{ .Values.infisical.resyncInterval }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        envSlug: {{ .Values.infisical.environment | quote }}
        secretsPath: {{ .Values.infisical.secretsPath | quote }}
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: {{ .Values.namespace }}
  managedKubeSecretReferences:
    - secretName: tumiki-cloud-api-env
      secretNamespace: {{ .Values.namespace }}
      creationPolicy: Owner
