apiVersion: v1
kind: Service
metadata:
  name: tumiki-cloud-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tumiki-cloud-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tumiki-cloud-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
