name: Fetch Vercel Environment Variables
description: Vercel から環境変数を取得して .env ファイルに保存する再利用可能なアクション

inputs:
  vercel-token:
    description: Vercel API トークン
    required: true
  environment:
    description: 環境名 (preview, production)
    required: true
  output-file:
    description: 出力する .env ファイルのパス
    required: false
    default: .env.local

outputs:
  env-file:
    description: 作成された環境変数ファイルのパス
    value: ${{ inputs.output-file }}

runs:
  using: composite
  steps:
    - name: Generate cache key
      id: cache-key
      shell: bash
      run: |
        ENVIRONMENT="${{ inputs.environment }}"
        # 環境とワークフローランIDを組み合わせてキャッシュキーを生成
        # 同じワークフロー実行内でのみキャッシュを共有
        CACHE_KEY="vercel-env-${ENVIRONMENT}-${{ github.run_id }}"
        echo "cache-key=${CACHE_KEY}" >> $GITHUB_OUTPUT

    - name: Restore cached environment variables
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.output-file }}
        key: ${{ steps.cache-key.outputs.cache-key }}

    - name: Vercel から環境変数を取得
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -eo pipefail

        ENVIRONMENT="${{ inputs.environment }}"
        OUTPUT_FILE="${{ inputs.output-file }}"
        VERCEL_TOKEN="${{ inputs.vercel-token }}"

        echo "Vercel から環境変数を取得します（環境: ${ENVIRONMENT}）"
        echo "出力ファイル: ${OUTPUT_FILE}"

        # vercel env pull: 環境変数をローカルファイルにエクスポート
        # 注: vercel pull は vercel build/dev を使う場合のみ必要。env pull は独立して動作する
        if ! pnpm exec vercel env pull "${OUTPUT_FILE}" --environment="${ENVIRONMENT}" --token="${VERCEL_TOKEN}" 2>/dev/null; then
          echo "❌ Vercel env pull コマンドが失敗しました。詳細を表示します:"
          pnpm exec vercel env pull "${OUTPUT_FILE}" --environment="${ENVIRONMENT}" --token="${VERCEL_TOKEN}"
          exit 1
        fi

        if [ ! -f "${OUTPUT_FILE}" ]; then
          echo "❌ Vercel から環境変数の取得に失敗しました（ファイルが作成されませんでした）"
          exit 1
        fi

        echo "✅ Vercel から環境変数を取得しました"
        echo "ファイルサイズ: $(wc -c < "${OUTPUT_FILE}") bytes"

    - name: Cache environment variables
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.output-file }}
        key: ${{ steps.cache-key.outputs.cache-key }}

    - name: Verify cached file
      if: steps.cache-restore.outputs.cache-hit == 'true'
      shell: bash
      run: |
        OUTPUT_FILE="${{ inputs.output-file }}"
        echo "✅ キャッシュから環境変数を復元しました"
        echo "ファイルサイズ: $(wc -c < "${OUTPUT_FILE}") bytes"
